Add EmployeeUser CRUD and GraphQL Resolvers
uwblueprint/sistering pull request #111
Opened 2022-01-30 21:05 UTC by jiarucao

## Ticket link

Addresses second half of #29 

## Implementation description
* Implement CRUD methods:
  - getEmployeeUserById
  - getEmployeeUserByEmail
  - getEmployeeUsers
  - createEmployeeUser
  - updateEmployeeUserById
  - deleteEmployeeUserById
  - deleteEmployeeUserByEmail

* Create corresponding GraphQL resolvers and DTOs

## Steps to test
1. Start docker and run `docker-compose up --build`
2. Apply the lasted migration files by running `docker exec -it sistering_backend /bin/bash` and `npx prisma migrate deploy`. 
3. We need row(s) in the posting and branch tables for testing. You can either create those using the corresponding GraphQL endpoints or use raw SQL. 
4. Go to http://localhost:5000/graphql
5. Login using an admin user 
6. Then verify that all GraphQL queries and mutations introduced in this ticket work as expected

## What should reviewers focus on?
* Verify that GraphQL endpoints work as expected

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-01-31 23:50 UTC, sherryhli requested changes
Looks great overall! We don't need to resolve postings when dealing with employees so just pending the removal of that code

2022-01-31 23:50 UTC, sherryhli commented on backend/graphql/types/userType.ts
> +    postings: [ID!]!
I think employee-posting relationships are exclusively created from the posting side (meaning that when an admin creates/updates a posting, they will select some employees for it to act as POCs). As far as my understanding goes, there isn't a case when we need to manually associate an employee to some postings from the employee side. This means we do not need the `postings` field as part of the `CreateEmployeeUserDTO` and `UpdateEmployeeUserDTO` input types, nor do we need to return `postings` in the `EmployeeUserResponseDTO`.

Sorry for the extra work and not specifying this in the ticket! However, it'd be nice to not pay the performance cost of writing/reading data we don't need.

cc @JoshuaYe @LenaNguyen for confirmation

2022-01-31 23:50 UTC, sherryhli commented on backend/services/implementations/postingService.ts
> -      userId: String(employee.userId),
**Note to self:** possibly need a new ticket to modify `getPosting` to include all Employee fields of the point-of-contacts (e.g. email, first name, last name, etc). This is required for the posting details page in the volunteer browsing flow. Alternatively, could make it the frontend's responsiblity to fetch employee details in a separately request using IDs returned from the `getPosting` query.

Posting GraphQL queries currently return nested `EmployeeResponseDTO` objects, decide whether or not we want to change `EmployeeResponseDTO` to `EmployeeUserResponseDTO`.

cc @LenaNguyen

2022-01-31 23:50 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +          postings: true,
As mentioned in the GraphQL types file, we do not require `postings` info from employee queries so this `include` is not needed. Likewise for the other get functions please.

2022-01-31 23:50 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +                },
Not needed

2022-01-31 23:50 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +            },
Not needed

2022-01-31 23:50 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +                },
This is still required though (FYI)

2022-02-02 01:18 UTC, JoshuaYe commented on backend/graphql/types/userType.ts
> +    postings: [ID!]!
This is correct

2022-02-02 03:58 UTC, LenaNguyen commented on backend/graphql/types/userType.ts
> +    postings: [ID!]!
Yup, seems right to me

2022-02-05 05:46 UTC, sherryhli requested changes
One more thing related to the deletion of both volunteers and employees, please see comment below for details

2022-02-05 05:46 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +import { PrismaClient, User, Skill, Branch, Posting } from "@prisma/client";
Nit: please remove the unused `Posting` import

2022-02-05 05:46 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +              },
I think the rollback should also include reverting the branch ID right?

```suggestion
              },
              branch: {
                connect: { id: Number(oldEmployeeUser!.branchId) },
              },
```

2022-02-05 05:46 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +                    }),
Hmm, I don't think this rollback is having the intended effect. `deletedEmployee` will not have any associated postings due to the `set: []` done on postings in the initial update within the transaction.

However, I think the solution is actually pretty simple 😄 Based on beahviour seen in `deletePosting` in `PostingService`, Prisma will automatically delete join table records when deleting from one of the associated relations, so the explicit `set: []` on postings isn't necessary. (In the case of postings, there are join table records for branches, skills, and employees, all of which are automatically deleted)

Let's convert that initial update to be a query instead, which fetches the employee + associated postings data prior to the delete. This gives us all the necessary fields needed to revert in the case of a firebase deletion failure. The volunteer deletion method suffers from the same issue too so let's change that as well.

2022-02-05 05:46 UTC, sherryhli commented on backend/types.ts
> +export type EmployeeDTO = {
Nit: let's call it `EmployeeUserDTO` for consistency with the other employee types

2022-02-11 01:14 UTC, jiarucao commented on backend/services/implementations/userService.ts
> +                    }),
Removed! But didn't need to add that query since the `delete` call returns the deleted object :)

2022-02-13 20:51 UTC, sherryhli requested changes
Two very minor things and then this is good to go!

2022-02-13 20:51 UTC, sherryhli commented on backend/types.ts
> +export type UpdateEmployeeUserDTO = Omit<EmployeeUserRequestDTO, "id"> & {
I don't think password is an updatable field (can only be reset via special reset flow), it should be omitted from the `UpdateEmployeeUserDTO` type

2022-02-13 21:01 UTC, merged