Add brand colours to theme
uwblueprint/sistering pull request #116
Opened 2022-02-03 16:41 UTC by LenaNguyen

## Ticket link

Closes #113 

## Implementation description
[Designs](https://www.figma.com/file/6zTSxaydHqW9YDmxr4wF1f/Sistering-Design-System)

* Added a colour scheme called `brand` which was generated using [Smart Swatch](https://smart-swatch.netlify.app/#7000E6). This is recommended by [Chakra](https://chakra-ui.com/docs/theming/theme#colors) so it will handle hover state, disabled state, etc. and make the component a shade darker or lighter. 
*  Set the default color scheme to `brand` so components that have a color (i.e. not gray like inputs, dividers, etc) will render purple by default unless overridden with props or theme.

* This PR doesn't include tags. I plan on following up with designers. 

## What should reviewers focus on?
* Check that colours are the same as expected designs. Sample components are rendered on the default page for now. They'll be removed before the pr is merged.

Designs:
![image](https://user-images.githubusercontent.com/43686735/152387030-5da89953-5152-4ee9-b244-880cbeadb72b.png)

Implementation:
![image](https://user-images.githubusercontent.com/43686735/152387258-431bb8fb-9243-4574-9fd2-8e23772bf866.png)

## Checklist
- [x] My PR name is descriptive and in imperative tense
- x ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-03 16:42 UTC, LenaNguyen commented on frontend/src/components/pages/Default.tsx
> +      </Tabs>
These will be removed before the pr is merged. Just put them here to display changes.

2022-02-03 16:44 UTC, LenaNguyen commented on frontend/src/theme/colors.ts
> +	},
I'm using the "hue down" palette from [Smart Swatch](https://smart-swatch.netlify.app/#7000E6) because on hover, Chakra sets the component colour (at least for buttons) to "brand.600". The hover colour in designs is `#4b00b4` .

2022-02-04 01:21 UTC, sherryhli requested changes
Minor linting issue, otherwise LGTM!

2022-02-04 01:21 UTC, sherryhli commented on frontend/src/components/pages/Default.tsx
> +      </Tabs>
Feel free to keep them for now, there's a `DesignSystemDisplay` component in this file that's currently used to demo all styles, tabs and buttons can be moved into there

2022-02-04 01:21 UTC, sherryhli commented on frontend/src/theme/colors.ts
> +	  50: '#f0e3ff',
Do you mind addressing the prettier warnings? `yarn fix` should do the trick

2022-02-04 01:56 UTC, MatoPlus commented on frontend/src/components/pages/Default.tsx
> +      <ChakraButton textStyle="button-regular">Default</ChakraButton>
Just curious, will we be deprecating Button for ChakraButton?

2022-02-04 02:36 UTC, sherryhli commented on frontend/src/components/pages/Default.tsx
> +      <ChakraButton textStyle="button-regular">Default</ChakraButton>
I think so, pretty sure all current uses of `Button` are in starter code components so can safely be moved eventually

2022-02-04 17:33 UTC, sherryhli commented on frontend/src/theme/colors.ts
>    green: {
Would you mind adding in 2 other colour changes? @krystaltruong has just updated the design system Figma file with the following:
* Dark green is now `#3C4B00`
* Text default is now `#333333`

2022-02-05 04:04 UTC, LenaNguyen commented on frontend/src/components/pages/Default.tsx
> +      </Tabs>
moved them to the bottom of `DesignSystemDisplay`
![image](https://user-images.githubusercontent.com/43686735/152628034-59ae3921-2ff7-444c-b1f7-0bda327af6d0.png)

2022-02-05 04:22 UTC, sherryhli approved these changes
LGTM 🚢

2022-02-06 14:46 UTC, merged