Tweak signup cchema for volunteer SelectAvailability requirement
uwblueprint/sistering pull request #134
Opened 2022-02-06 22:25 UTC by MatoPlus

## Ticket link

Closes #

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-11 03:30 UTC, MatoPlus commented
Not too sure why yarn install for backend is failing... @uwblueprint/sistering-w22-pls any ideas? I will come back to this and do some digging.

2022-02-13 20:35 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +      />
This should be removed later, here to demo purposes

2022-02-13 22:01 UTC, LenaNguyen requested changes
Great work! Did you get a chance to ask designers about whether the input should be disabled when the shift hasn't been checkmarked? I think it might prevent confusion among users. They might think they signed up for a shift if they wrote a note but forgot to checkmark

2022-02-13 22:01 UTC, LenaNguyen commented on frontend/src/utils/TimeUtil.ts
> +}
on a scale of 0 - 100 how bug free do you think this code is 😛 if we're going to do a lot of date manipulation, it might be worth it to investigate using `Moment.js` . Out of the scope for this ticket though. TY for writing this!

2022-02-13 22:40 UTC, MatoPlus commented on frontend/src/utils/TimeUtil.ts
> +}
I think this should be okay for our purpose. Worst case scenario, we fetch start/end dates in different timezones and this gives us garbage. We should definitely add Moment.js when we get the chance though👍

2022-02-13 22:42 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +      <Checkbox minWidth={300} mr={170}>
I don't think the content in the checkbox is not guaranteed to be less than 300px. This is a safe guard imo!

2022-02-13 22:44 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +  const [note, setNote] = React.useState("");
Definitely! this is a temporary solution. It might make FE dev a lot easier if we choose to look into some minimal state management like `unstated-next`

2022-02-13 22:46 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +          onChange={(event) => setNote(event.target.value)}
hmm I'm not sure if we want that. It would make the UX a bit jank since users can't type empty spaces. Users could get confused about why empty spaces are not working. Imo, this looks good as long as we trim our data to be passed to calls. Thoughts?

2022-02-13 22:46 UTC, MatoPlus commented
@LenaNguyen for context, it might make sense to look at this PR side to side with #146

2022-02-13 23:35 UTC, LenaNguyen commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +      <Checkbox minWidth={300} mr={170}>
Ohh mb this is onchange. We would wanna trim the input onblur

2022-02-13 23:36 UTC, LenaNguyen commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +          onChange={(event) => setNote(event.target.value)}
Ohh mb this is onchange! Yeah agreed. We would wanna trim the input onblur or whenever we set the values for the API call

2022-02-16 13:33 UTC, LenaNguyen submitted a review, later dismissed
LGTM!

2022-02-20 21:19 UTC, LenaNguyen approved these changes

2022-02-20 21:25 UTC, merged