Boya/volunteer-posting-card
uwblueprint/sistering pull request #135
Opened 2022-02-06 23:11 UTC by Boyazhang1

## Ticket link

Closes #82 

## Implementation description
- created a volunteer posting card component that is used in the volunteer postings page, based on the Figma design

## Steps to test

In VolunteerPostingsPage.tsx, filter the postingArr (which consists of sample data) to see each volunteer posting card. 
Expected results: 
<img width="1294" alt="Screen Shot 2022-02-06 at 1 30 08 PM" src="https://user-images.githubusercontent.com/82241706/152703550-6e6b3ce5-5047-4106-b84a-aa9240b2bc0e.png">

## What should reviewers focus on?
- UI matches figma, chakra-ui components are being used correctly 
- prop type and values are correct
- whether types are correct/appropriate

## Checklist
- [x ] My PR name is descriptive and in imperative tense
- [ x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ x] I have run the appropriate linter(s)
- [ x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-10 23:04 UTC, sherryhli requested changes
Great work so far! 😄 A lot of my comments relate to styling, although I realize that the designs may have changed between the time you started working on this ticket and now. Sorry for adding these extra requirements! However, it'd be nice if we can get these changes in now so that we're making use of the theming system

Please also resolve the lint + formatter warnings by first running `yarn fix` in the frontend, and then manually addressing the remaining issues
```
docker exec -it sistering_frontend /bin/bash -c "yarn fix"
```

Note that I did not review the posting page as that will be merged in a separate PR. Feel free to keep it for now to simplify testing, but please remove it from this branch prior to merging

2022-02-20 02:38 UTC, LenaNguyen reviewed
Thought I'd jump in here to let you know about the util that Albert already made for formatting dates :)

2022-02-20 02:38 UTC, LenaNguyen commented on frontend/src/components/volunteer/PostingCard.tsx
> +            })}`}
you could use `formatDateString` in `frontend\src\utils\DateUtils.ts`

2022-02-20 02:38 UTC, LenaNguyen commented on frontend/src/components/volunteer/PostingCard.tsx
> +            })}
`formatDateString` in `frontend\src\utils\DateUtils.ts`

2022-02-20 02:38 UTC, LenaNguyen commented on frontend/src/theme/index.ts
> +        },
hmm this is already merged in `main` . Not sure why they're showing up as changes here. Can you try rebasing?

2022-02-20 17:26 UTC, sherryhli requested changes
Apologies for the delay in reviewing, just a couple minor things left!

There looks to be a lot of changes from other PRs that are showing up in the diff, can you make sure to only include your own changes? Your branch is up to date with `main` so I'm not sure what exactly is happening here, so perhaps a simpler fix is to create a new branch with only the `PostingCard.tsx` file (and any other dependent changes) and make a new PR. You can briefly include the browse posting page for testing but we'll remove it prior to merging.

2022-02-20 17:26 UTC, sherryhli commented on frontend/src/components/volunteer/PostingCard.tsx
> +      <VStack p={6} align="start" spacing="12px">
Padding should be 36px for top and bottom and 40px for left-right, doesn't look like this is the case with p={6}

Figma:
<img width="759" alt="Untitled" src="https://user-images.githubusercontent.com/30205929/154854585-c84cd705-70cf-4205-8a04-7d83d1ca78af.png">

2022-02-20 17:26 UTC, sherryhli commented on frontend/src/components/volunteer/PostingCard.tsx
> +            {`${formatDateString(startDate)} - ${formatDateString(endDate)}`}
Hmm there's actually a difference between the format produced by the util function and what's expected for this view (missing year). Can you please create a new helper function in DateUtil.ts (maybe something called `formatDateStringWithYear`) and use that instead?

2022-02-20 17:26 UTC, sherryhli commented on frontend/src/components/volunteer/PostingCard.tsx
> +        <Divider mb={1} />
I think there should be a margin of 16px above and below the divider

2022-02-20 17:26 UTC, sherryhli commented on frontend/src/components/volunteer/PostingCard.tsx
> +          <ButtonGroup spacing="4" size="md">
Spacing a bit too wide, should be 10px

2022-02-20 18:12 UTC, sherryhli commented
@Boyazhang1 as #149 is also ready for review, feel free to move the PostingCard changes over and I can review both together 🙂

2022-02-21 03:13 UTC, closed without merging