Admin create posting "Review and Post" page UI
uwblueprint/sistering pull request #136
Opened 2022-02-06 23:25 UTC by briantu

## Ticket link

Closes #59 

## Implementation description
* Created the posting review component `CreatePostingReview.tsx` (under `frontend/src/components/admin/posting`) and the review page `CreatePostingReviewPage.tsx` (under `frontend/src/components/pages/admin/posting`) in which the component is mounted
* Routed the page to `/admin/posting/create/review`
* Used `PostingContext` to fetch posting data to be displayed in the review page
* Added following components to `frontend/src/components/common`:
  * `BasicInfoGridItem.tsx`
  * `PocCard.tsx`
  * `SkillTag.tsx`
  * `ScheduledShiftsTr.tsx`

## Steps to test
1. Run the application locally `docker-compose up --build`
2. Log in and click on "Edit Posting" tab on the default page and enter some dummy information in the form
3. Go back to the default page and click on "Review Posting" tab
4. Verify the changes on the review posting page. Try jumping back and forth between these pages and manipulating the data. Note that you should not reload the app as that will clear the app state. This means you should not refresh or navigate by manually changing the URL, instead, navigate using the tabs and "Go Back" buttons)

## What should reviewers focus on?
* Does `CreatePostingReview.tsx` follow the Figma design?
* Is the page properly showing the posting info (from context)?

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-09 16:40 UTC, LenaNguyen requested changes

2022-02-09 16:40 UTC, LenaNguyen commented on frontend/src/components/common/SkillTag.tsx
> +};
Now that the theme is updated, let's create a new variant called "brand" (since this is the tag with brand colours) and specify these settings in the theme. Then you can just import the `Tag` component from Chakra and set `variant` to be `brand`. 

This [video](https://egghead.io/lessons/react-create-custom-variants-in-chakra-ui?utm_source=rss&utm_medium=feed&utm_campaign=pro_rss_feed) from the tutorial might be helpful.

[Tag theme source](https://github.com/chakra-ui/chakra-ui/blob/main/packages/theme/src/components/tag.ts)

2022-02-09 16:40 UTC, LenaNguyen commented on frontend/src/components/common/PocCard.tsx
> +        <EmailIcon color="#C4C4C4" w="20px" h="20px" />
hm it looks like this colour is not in the chakra theme or our custom theme (same with the border colour). We should be using colours from the themes instead of hardcoding though. 
We'll need to chat with designers and see if we need to add more colours to our custom theme. I'll make a separate ticket to clean this up in the future if we have time.

2022-02-09 16:40 UTC, LenaNguyen commented on frontend/src/components/common/ScheduledShiftsTr.tsx
> +import React from "react";
IMO this component can just be in `/admin/posting` instead of `/common` because it's pretty specific to the layout of admin posting and this is the only place where we display shifts like this.

2022-02-11 00:56 UTC, briantu commented on frontend/src/App.tsx
> +import "@fontsource/raleway/700.css";
Yeah, it's used for the number of the step on the top left. That's the only thing that requires raleway bold I think 😂

2022-02-11 01:25 UTC, briantu commented on frontend/src/components/common/PocCard.tsx
> +        <EmailIcon color="#C4C4C4" w="20px" h="20px" />
Yeah sure, had a chat with Krystal and we decided to use the text gray color instead

2022-02-11 01:31 UTC, briantu commented on frontend/src/App.tsx
> +import "@fontsource/raleway/700.css";
I don't need raleway medium anymore, so I'll remove that. But inter medium font weight is used in `ScheduledShiftsTr`, `BasicInfoGridItem` and `PocCard`

2022-02-11 03:16 UTC, LenaNguyen requested changes
Almost done!

2022-02-11 03:16 UTC, LenaNguyen commented on frontend/src/theme/index.ts
> +              borderRadius: "full",
add `color: text.white`

2022-02-11 03:16 UTC, LenaNguyen commented on frontend/src/components/common/BasicInfoGridItem.tsx
> +    </GridItem>
Can you move this out of a `GridItem` so that it can be used in more scenarios. This will make it more reusable.
It'd be great if you could rename to something more descriptive like `LabelledText` and have the props be `label` and `text` instead.

2022-02-13 20:38 UTC, merged