Add Posting Details Page UI and Query
uwblueprint/sistering pull request #140
Opened 2022-02-11 15:04 UTC by albertlai431

## Ticket link
Closes #81

## Implementation description
* Added types for Posting, Branch, Employee, Shift, and Skill
* Created routing for Posting Details Page
* Used PocCard UI from #136 
* Created query to fetch Posting data and the associated Posting Details Page UI

## Steps to test
1. `docker-compose up --build`
2. Navigate to http://localhost:5000/graphql and run the following mutations:

```graphql
# Create Branch
mutation{
  createBranch(branch: {
    name: "NYC"
  }){
    id
    name
  }
}

# Create Skill
mutation{
  createSkill(skill:{
    name: "Skill1"
  }){
    name
  }
}

# Create Posting
mutation {
  createPosting(posting: {
    branchId: 1
    skills: [1]
    employees: []
    title: "Test Posting"
    type: INDIVIDUAL
    status: DRAFT
    description: "lol",
    startDate: "2022-01-20"
    endDate: "2022-01-21"
    autoClosingDate: "2022-01-23"
    numVolunteers: 10
  }) {
    title
    type
    status
    description
    startDate
    endDate
    autoClosingDate
    numVolunteers
  }
}
```
3. Navigate to http://localhost:3000/volunteer/posting/1 and verify that the UI matches that specified in #81

## What should reviewers focus on?
* Verify that the query works and the UI matches that specified in #81

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-13 21:38 UTC, LenaNguyen requested changes
Run `yarn fix` after addressing the comments and rebasing to help with the linting warnings :)

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +import colors from "../../../../theme/colors";
You shouldn't need to import colors. You can just reference the colors from our theme using a string. See comments below

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +    <Box bg={colors.background.light} py={7} px={10} minH="100vh">
bg="background.light"

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +          bg={colors.background.white}
bg="background.white"

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +                      <Text textStyle="caption" color={colors.text.gray}>
color="text.gray"

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +                    {/* {postingDetails.employees.map((employee) => <PocCard />)} */}
remove this comment. we can add this code back when we need it

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +                    <Text textStyle="caption" color={colors.text.gray}>
color="text.gray"

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +      console.error(error.message);
hm not sure if we have a way of logging errors in the frontend. I'll get back to you on this, but we shouldn't be console logging them

2022-02-13 21:38 UTC, LenaNguyen commented on frontend/src/types/api/BranchType.ts
> +export type BranchResponseDTO = BranchDTO;
Just checking, these types aren't being used currently, right? You're just adding them preemptively? Same with the types for Shifts and Skills

2022-02-14 13:18 UTC, albertlai431 commented on frontend/src/App.tsx
> -              <PostingContextDispatcherContext.Provider
Oops must've been a mistake on my end when rebasing, it's fixed now!

2022-02-14 13:18 UTC, albertlai431 commented on frontend/src/components/common/PocCard.tsx
> +export default PocCard;
Yep, just rebased off main so it's updated with his version now

2022-02-14 17:35 UTC, albertlai431 commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +      console.error(error.message);
For visibility: I ended up just removing the error handling, to be addressed in a future ticket most likely

2022-02-14 20:13 UTC, LenaNguyen requested changes
Great work! Just a couple small things that I missed in my first review.

2022-02-14 20:13 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +// Description is the markdown description
does this comment need to be here? Also isn't the description rich text?

2022-02-15 05:01 UTC, LenaNguyen approved these changes
Those were some speedy changes! Great work!
![](https://media.giphy.com/media/afiHu8BY4UDiKjRcDy/giphy.gif)

2022-02-15 22:05 UTC, merged