Add API call functionality to create posting
uwblueprint/sistering pull request #147
Opened 2022-02-13 23:44 UTC by briantu

## Ticket link

Closes #88 

## Implementation description
* Added the create posting mutation in `CreatePostingReviewPage`
* Added two buttons ("Save as Draft" and "Post") in `CreatePostingReviewPage` that call the create posting mutation
  * Save as Draft: creates posting with status `DRAFT`
  * Post: creates posting with status `PUBLISHED`
* `CreatePostingReviewPage` gets posting data using `PostingContext`

## Steps to test
1. Run the application locally `docker-compose up --build`
2. Create a branch in your local database for the posting to use
3. Click on the "Edit Posting" tab on the default page and enter the branch id of the branch you just created. 
4. Add other dummy information (be sure to include the dates for "Start Date", "End Date", and "Auto-Closing Date").
5. Click on the "Review Posting" tab and click the "Save as Draft" or "Post" button
6. Check that the posting was successfully created in your local database

## What should reviewers focus on?
* Create posting functionality works as expected
* Correct coding practices for calling API

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-13 23:46 UTC, briantu commented
Question to consider - how are we handling front-end error messaging? (e.g. when API call to create posting fails)

2022-02-17 22:21 UTC, LenaNguyen requested changes
sorry for the late review .-.

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +  if (loading) console.log("Submitting...");
Remove this after adding `isLoading` prop to buttons

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +      <Button
You can add a loading state to buttons via props. See [docs](https://chakra-ui.com/docs/form/button#button-loading-state). `isLoading={loading}`

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +      <Button
`isLoading={loading}`

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +  if (error) console.log(`Submission error! ${error}`);
We should get some designs for what the user should see if there's an error.

For now let's just `window.alert(error)`.

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +  const [createPosting, { data, loading, error }] = useMutation(CREATE_POSTING);
If you're not using data, put an underscore at the beginning of the name like `_data` to ignore the lint warning

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +        }}
```suggestion
        onClick={() => 
          createPosting({
            variables: {
              posting: { ...postingToCreate, status: "DRAFT"  },
            },
          });
        }
```

2022-02-17 22:21 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +        }}
```suggestion
        onClick={() => 
          createPosting({
            variables: {
              posting: { ...postingToCreate, status: "PUBLISHED" },
            },
          });
        }
```

2022-02-18 01:56 UTC, briantu commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +      <Button
Done! Also I created an `isDraftClicked` boolean to track which button is clicked for the loading state.

2022-02-18 01:56 UTC, briantu commented on frontend/src/components/pages/admin/posting/CreatePostingReviewPage.tsx
> +  const [createPosting, { data, loading, error }] = useMutation(CREATE_POSTING);
Decided to completely remove the `data` variable

2022-02-18 02:20 UTC, LenaNguyen approved these changes
Nice discovery of `useBoolean`!
![](https://media.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif)

2022-02-18 02:41 UTC, merged