Implement admin "select shift times" calendar
uwblueprint/sistering pull request #150
Opened 2022-02-18 01:13 UTC by lambo-liu

## Ticket link

Closes #102 

## Implementation description
* Leveraged FullCalendar to create the admin shifts calendar.
* To use the calendar:
- * Click to create a new event
- * Drag the bottom of the event card to change the length of the event
- * Click on the card to prompt deletion modal

## Steps to test
1. Navigate to `http://localhost:3000/admin/posting/create/shifts` and play around with the calendar!
2. Feel free to add a `console.log(events)` in the code to check the output data

## What should reviewers focus on?
* Correct usage of FullCalendar
* Intuitive feel to the calendar

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-20 18:56 UTC, LenaNguyen commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +    const newEvents = events.slice();
I believe it's best practice to pass in all your data as params instead of referencing something declared elsewhere. It makes it easier to read/understand and potentially test.

2022-02-20 18:56 UTC, LenaNguyen commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +    }
optionally you could use `const newEvent = newEvents.find(event => newEvent.id === oldEvent.id)`

2022-02-20 18:56 UTC, LenaNguyen commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +      const newEvents = events.slice();
pass in `events` as a param

2022-02-20 18:56 UTC, LenaNguyen commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +      }
optionally you could use `newEvents.indexOf()`

2022-02-20 18:56 UTC, LenaNguyen commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +              : ""}
pls move this into the utils folder. Rename the file called `DateUtils.tsx` into `DateTimeUtils.tsx` and add it there

2022-02-24 21:51 UTC, sherryhli requested changes
Looking good, thanks for fiddling around with CSS to get the correct styling! One main thing is to change  `events` to a prop, the rest are just small nits.

2022-02-24 21:51 UTC, sherryhli commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +  const [events, setEvents] = React.useState<Event[]>([]);
Nit: let's import `useState` and use it directly

```suggestion
  const [events, setEvents] = useState<Event[]>([]);
```

2022-02-24 21:51 UTC, sherryhli commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.css
> +  font-family: "Work Sans", sans-serif;
Have checked with designers on whether this is the actual intended font? Only Raleway and Inter are part of our design system

2022-02-24 21:51 UTC, sherryhli commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +      />
Suggestion: might be nice to add `scrollTime="09:00:00"` so that the default view starts at 9 am instead of 12 am. Could get some design input on this

2022-02-24 21:51 UTC, sherryhli commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +  const [events, setEvents] = React.useState<Event[]>([]);
Also I think `events` should be a prop passed in from the parent component (CreatePostingShifts #164) so that it can have access to the events, perform error checking, and add update the global posting context.

2022-02-25 02:41 UTC, LenaNguyen reviewed
Just tested it out and the calendar looks sooo good! 🤩

2022-02-27 21:43 UTC, lambo-liu commented
Fixed up the details! Please let me know if there's anything else I can clean up 🛁

2022-03-01 02:56 UTC, sherryhli requested changes
UI looks great but we do need to rework the state management a bit. Again, sorry for not catching this earlier and let me know if you have any questions!

2022-03-01 02:58 UTC, sherryhli commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +  const [events, setEvents] = useState<Event[]>(shifts);
We need to lift the state up to the parent component (in this case it's `CreatePostingShiftsPage` and eventually it'll be `CreatePostingShifts` from #164 when merged). This is so that the create shifts component can update the posting context (global state) with shifts data along with other posting fields.

Sorry, I didn't completely think this through when I made my previous comment, but the change is a bit more involved than just adding a `shifts` prop. We need the parent component to maintain the `events` state and all functions for manipulating state (e.g. `addEvent`, `changeEvent`, `deleteEvent`) should be passed in as props (and defined in the parent). The event count state should similarly be maintained in the parent and a function for getting the next event ID should also be provided as a prop.

Let me know if any further clarification is needed!

2022-03-06 04:32 UTC, sherryhli approved these changes
Awesome stuff! 🚀 Go ahead and merge if you need to unblock yourself, though there is a one-liner change needed

2022-03-06 04:32 UTC, sherryhli commented on frontend/src/components/admin/ShiftCalendar/ShiftCalendar.tsx
> +        slotLabelInterval="01:00"
Let's add this prop so that event start and end times are stored in UTC instead of local time

```suggestion
        slotLabelInterval="01:00"
        timeZone="UTC"
```

2022-03-06 06:23 UTC, sherryhli approved these changes
🚢🚢🚢

2022-03-06 06:24 UTC, merged