complete volunteer posting card, postings page, postings filter
uwblueprint/sistering pull request #166
Opened 2022-02-21 03:11 UTC by Boyazhang1

## Ticket link

Closes #82 #83 #117

## Implementation description
- refactor posting card according to comments on PR
- created a page that displays events and regular volunteer opportunities (/volunteer/postings), fetches data via a graphQL query
- created an empty event component to display in the case where there are no active events / regular volunteer opportunities
- create filter feature for week/month/all shifts timeframes

## Steps to test
Navigate to http://localhost:5000/graphql and run the mutation (see: https://github.com/uwblueprint/sistering/pull/140) multiple times with different startDates 
Navigate to http://localhost:3000/volunteer/postings and verify: 
- API call receives the correct data
- Implementation UI matches Figma for #83 Volunteer Browse Postings Page
- Verify the definition of what an volunteer opportunity/event is (line 154 in volunteerPostingsPage.tsx)
- ensure filter functionality works with their timeframe

## What should reviewers focus on?
- Implementation UI matches Figma for #83 Volunteer Browse Postings Page
- ensure filter functionality works with their timeframe

## Checklist
- [ x] My PR name is descriptive and in imperative tense
- [ x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x ] I have run the appropriate linter(s)
- [x ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-23 06:59 UTC, sherryhli requested changes
Awesome to see this come together! It's almost good to go, a bit more polishing left to do. Thanks for your patience with this! 😄

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +const MS_PER_WEEK = 604800000;
To quickly prove the correctness of calculated values, a common practice is to show the arithmetic

```suggestion
const MS_PER_WEEK = 7 * 24 * 60 * 60 * 1000;
```

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +`;
To improve performance, we can omit all the fields that are not needed for this component. This will require creating a custom local type definition that excludes all the extraneous fields in `PostingResponseDTO`, the TypeScript `Omit` type can be used, e.g.

```ts
type Posting = Omit<PostingResponseDTO, "shifts" | "employees" | "type" | "status" | "numVolunteers">
```

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +  const [filter, setFilter] = useState<string>("week");
```suggestion
  const [filter, setFilter] = useState<FilterType>("week");
```

where `FilterType` is a type defined in this file:
```ts
type FilterType = "week" | "month" | "all";
```

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +      startDate.getTime() - Date.now() > 0 &&
Small edge case

```suggestion
      startDate.getTime() - Date.now() >= 0 &&
```

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +  // should posting.startDate type be declared as string instead on frontend?
Yes, good catch! The dates returned in the posting query are all strings in YYYY-MM-DD format, Please update the `PostingDTO` type to reflect this.

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +  const dateCompareUtil = (start: Date, filterType: string): boolean => {
```suggestion
  const dateInRange = (start: Date, filterType: string): boolean => {
```

Also, since this function will likely be reused for other filter components, it'd be a good idea to add this to `DateUtils.ts` 🙂

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +    <Box bg="background.light" pt="48px" minHeight="100vh">
Please add left/right padding (101px) and bottom padding (64px)

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +        <HStack justify="space-between" bg="#F4F4F4" pb="36px">
This should be the same as background.light which is specified for the enclosing Box

```suggestion
        <HStack justify="space-between" pb="26px">
```

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +            <Box key={posting.id} pt="36px">
I think the padding between cards should be 24px

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +        </Text>
Missing some padding on the top here
![image](https://user-images.githubusercontent.com/30205929/155273065-446126a0-40dd-4f24-b210-919731d3ce51.png)

2022-02-23 06:59 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +    } else {
Just curious, in what case would e.target.value be falsey?

2022-02-27 07:07 UTC, Boyazhang1 commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +    } else {
not sure why but the chakraUI select element provides a value to the default, so if the selected value is blank, it sets the filter type to weekly which is the intended behavior

2022-03-01 00:26 UTC, sherryhli commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +  const [filter, setFilter] = useState<string>("week");
Using a type assertion should do the trick, i.e.
```ts
 e.target.value as FilterType
```

2022-03-01 02:03 UTC, sherryhli requested changes
Last couple of minor things and then this is good to go!

2022-03-01 02:03 UTC, sherryhli commented on frontend/src/utils/DateUtils.ts
> +export const dateInRange = (start: string, filterType: string): boolean => {
```suggestion
export const dateInRange = (start: string, filterType: FilterType): boolean => {
```

Let's move the `FilterType` definition into a new file under `frontend/src/types/DateFilterTypes.ts` so it can be shared by this util and the postings page component

2022-03-04 01:37 UTC, sherryhli approved these changes
LGTM! 🚢

2022-03-04 01:38 UTC, merged