Add Admin Posting Details Page
uwblueprint/sistering pull request #167
Opened 2022-02-23 14:12 UTC by albertlai431

## Ticket link

Closes #155 

## Implementation description
* Refactored VolunteerPostingDetails page
* Created routing for AdminPostingDetails page
* Created query to fetch Posting data and the associated Admin Posting Details Page UI

## Steps to test
1. `docker-compose up --build`
2. Navigate to http://localhost:3000/admin/posting/1 and verify that the UI matches that specified in #155 

## What should reviewers focus on?
* Verify that the query works and the UI matches that specified in #155

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-02-23 18:02 UTC, LenaNguyen requested changes
Just one small thing!

2022-02-23 18:02 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
>                    <Divider />
Can you check with design to see if the bottom part of the posting details should be included for the **admin** view? We might need to include the deadline at the bottom but without the button.

If so, we should include this bottom part in the `PostingDetails` component and add a string prop like `footerButtonText`. If the prop is null, then don't render the button. 

![image](https://user-images.githubusercontent.com/43686735/155378769-e2dd2100-13c1-4d9f-8383-ca61d7feb20f.png)

2022-02-24 12:55 UTC, albertlai431 commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
>                    <Divider />
Yep, just confirmed with @krystaltruong that the footer for the admin view should contain the deadline but not the button! I'll make the requested changes.

2022-02-25 01:22 UTC, LenaNguyen approved these changes
![](https://media.giphy.com/media/qMi9FmYD8zXH15Fcw3/giphy.gif)

2022-02-25 01:38 UTC, sherryhli commented on frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
> +  query Posting($id: ID!) {
Small suggestion: let's prefix all operation names with the component they're located in, this is a common practice with GraphQL as it helps with debugging

```suggestion
  query AdminPostingDetails_Posting($id: ID!) {
```

2022-03-01 18:22 UTC, albertlai431 commented on frontend/src/components/pages/admin/posting/AdminPostingDetails.tsx
> +  query Posting($id: ID!) {
Done!

2022-03-01 18:24 UTC, sherryhli approved these changes
Awesome, LGTM!

2022-03-01 18:26 UTC, merged