Rickson/volunteer select availability table headers
uwblueprint/sistering pull request #168
Opened 2022-02-25 00:09 UTC by MatoPlus

## Ticket link

Closes #119 

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-11 02:40 UTC, MatoPlus commented
The ticket also includes the submit button, etc. However, I'll create this in the datafetch ticket since we do not have a ticket yet.

2022-03-13 05:13 UTC, LenaNguyen requested changes
We can ignore the input prop type for now but we'll have to create a new type in the frontend similar to `frontend\src\types\api\ShiftTypes.ts`. It depends on how we do the data fetch but we may need to create a new endpoint that returns the shifts for a given posting and the signups for each shift where userId is the current user.

2022-03-13 05:13 UTC, LenaNguyen commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +                </option>
the hover color of the select should be gray.100

2022-03-13 05:13 UTC, LenaNguyen commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +                          />
We will need to persist which table rows have been checkmarked when we switch to another week. This can be done with the data fecth PR though.

2022-03-13 18:18 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingsPage.tsx
> +      {/* Temp */}
Oh thanks for pointing this out. I actually plan to remove all my new code to another new page in https://github.com/uwblueprint/sistering/pull/199. I'll likely just revert the changes done on this page.

2022-03-13 18:19 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +              ).length < 1 ? (
yea I like that. thanks for the pointer!

2022-03-13 18:20 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +                          />
indeed, we need to keep track of the shift states in the most top page in #199

2022-03-13 19:58 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +                </option>
I changed it for the Select component but I can't find a reliable way of applying the effect to vanilla option tags 🤔. I know there's a way to do it using react-select there seems to be nothing with chakra ui.

2022-03-13 20:19 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +              ).length < 1 ? (
I ended up reducing the redundancy with a variable within the mapping expression. I don't think we actually need a state here since otherwise, we'll need a state for each week.

2022-03-13 20:43 UTC, MatoPlus commented on frontend/src/theme/index.ts
> +      Table: {
credits to @lambo-liu for this : )

2022-03-21 13:48 UTC, LenaNguyen approved these changes
great work!

2022-03-28 17:36 UTC, merged