Create volunteer navbar
uwblueprint/sistering pull request #182
Opened 2022-02-27 23:13 UTC by briantu

## Ticket link

Closes #125 

## Implementation description
* Created `VolunteerNavbar.tsx` component in `/frontend/src/components/volunteer`
* Navbar tabs switch between `VolunteerShiftsPage.tsx` and the `VolunteerPostingsPage.tsx`
* Added navbar to those two pages

## Steps to test
1. Navigate to either `/volunteer/shifts` or `/volunteer/postings` route where the navbar is used
2. Check that the navbar tabs switch to the correct pages

## What should reviewers focus on?
* Navbar follows desgins
* Navbar correctly switches between the two pages

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-02 02:10 UTC, LenaNguyen commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +      <Flex h={14} alignItems="center" justifyContent="space-between">
How come the height of the navbar is less than the Figma designs? 14 corresponds to 56px but the Figma says 80px which is 20.

2022-03-02 02:12 UTC, LenaNguyen commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +                  py="16px"
same for the vertical padding. should this be 26px instead?

2022-03-02 03:38 UTC, briantu commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +      <Flex h={14} alignItems="center" justifyContent="space-between">
Oh whoops, I was eyeballing the height. Fixed!

2022-03-02 03:39 UTC, briantu commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +      <Flex h={14} alignItems="center" justifyContent="space-between">
Also, for some reason when I do `h={20}` for some reason the height goes to 90px, so I did "h=80px" instead.

2022-03-04 00:35 UTC, LenaNguyen requested changes
I was gonna suggest something about nested routing but since there's only two tabs it doesn't matter that much 😅 Anyways just two more small changes and it's good to go!

2022-03-04 00:35 UTC, LenaNguyen commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +          render={({ history }) => (
sorry for not catching this before, you don't need to use history. Instead it would be easier to wrap the `Tab` or the text in the `Tab` component in a [react router link](https://v5.reactrouter.com/web/api/Link). And set the link to be the page that we want to render.

2022-03-04 00:35 UTC, LenaNguyen commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +  defaultIndex: number;
Can you change this to be an [enum](https://www.typescriptlang.org/docs/handbook/enums.html) to make it more readable?

2022-03-04 01:49 UTC, LenaNguyen approved these changes
![](https://media.giphy.com/media/emMxYcyEZVO56NsBm8/giphy.gif)

2022-03-04 01:52 UTC, LenaNguyen approved these changes
beautiful rebase

2022-03-04 01:54 UTC, merged