Polish admin posting pages
uwblueprint/sistering pull request #203
Opened 2022-03-10 21:07 UTC by sherryhli

## Ticket link

Closes #138

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-14 21:15 UTC, sherryhli commented on frontend/src/components/admin/posting/CreatePostingShifts.tsx
> +      <div key={startDate}>
**More context:**
We need to set the initial date of the calendar to be in the week of the start date, which can be done via the `intialDate` prop passed to `FullCalendar`. The start date changes depending on user input on the create shifts page. However, FullCalendar does not re-render when the prop changes. This is a temp hack to force a re-render.

https://github.com/fullcalendar/fullcalendar-react/issues/57

2022-03-14 21:15 UTC, sherryhli commented on frontend/src/components/common/SideNavbar.tsx
> +    <Steps activeStep={activeStep} orientation="vertical" width="250px">
The circular number icon becomes distorted when the text spans multiple lines

2022-03-15 04:28 UTC, sherryhli commented on frontend/src/components/common/SideNavbar.tsx
> +    <Steps activeStep={activeStep} orientation="vertical" width="250px">
This is a temporary fix and does not work for smaller screens as it affects the centering of elements within the `Container`

2022-03-17 23:57 UTC, LenaNguyen requested changes
Looks really good! Thanks for making these changes :) Just a some small deviations from designs and a couple questions.

2022-03-17 23:57 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingBasicInfoPage.tsx
> +            labels={["Basic Information", "Time Slots", "Review and Post"]}
The sidenav needs the grey background to match the designs. It's #F3F3F3 in the designs so we may need to ask if that also maps to `background.dark`

2022-03-17 23:57 UTC, LenaNguyen commented on frontend/src/components/admin/posting/CreatePostingShifts.tsx
> +      </VStack>
The next/back footer should be stuck to the bottom of the screen:
![image](https://user-images.githubusercontent.com/43686735/158911866-5ef7e4fb-a734-4d1a-9ef5-7f7918a3b430.png)


If we're gonna refactor so that this creation flow is all in one page, then this change is probably better there instead of this pr though!

2022-03-17 23:57 UTC, LenaNguyen commented on frontend/src/components/admin/posting/CreatePostingShifts.tsx
> +      </VStack>
Made a ticket to refactor into one page #213

2022-03-17 23:57 UTC, LenaNguyen commented on frontend/src/components/admin/posting/CreatePostingShifts.tsx
> +      <div key={startDate}>
Wait if posting start date is not on a sunday, is it supposed to rerender? Bc it does not for me. 

Also, I realized if they make a posting that does not span the entire week, like wednesday to friday, the shift calendar will still allow you to create shifts for the entire week. It's kind of confusing bc when you input the dates, the format of the date doesn't say what day of the week it is.

![image](https://user-images.githubusercontent.com/43686735/158912493-9b60ee0f-d589-4948-84c2-da5cd4fc9fa2.png)

2022-03-18 01:58 UTC, LenaNguyen commented on frontend/src/components/pages/admin/posting/CreatePostingBasicInfoPage.tsx
> +            labels={["Basic Information", "Time Slots", "Review and Post"]}
I asked the designers it's actually `background.light`

2022-03-24 17:21 UTC, sherryhli commented
Did a rebase but did not address the side navbar design deviation. It's not quite as straightforward as I thought, having trouble making the the enclosing VStack span the entire height of the container and I'll need to fiddle with the styling a bit more.

This issue, along with a couple others are documented in #233 for round 2 of refinement. @LenaNguyen if you don't mind could we go ahead and merge this PR as is?

2022-03-24 19:06 UTC, LenaNguyen approved these changes
👏👏

2022-03-24 22:21 UTC, merged