Lambert/schedule review table
uwblueprint/sistering pull request #206
Opened 2022-03-13 01:48 UTC by lambo-liu

## Ticket link

Closes #156 
Closes #158 

## Implementation description
* Implemented the **schedule review table** and its table rows, which display all volunteer shifts of a certain week.
* Note that this table implementation is only for displaying the shifts in one week (passed in via props), and does not include the date navigation header.

## Steps to test
1. Add the following code to `Default.tsx`, importing components/variables when necessary:
```
<Container maxW="container.xl">
  <AdminScheduleTable schedule={TableTestData} />
</Container>
```
2. Check http://localhost:3000/ to see that `TableTestData` is rendered correctly. The test data includes three types of table rows, as specified in #156.

## What should reviewers focus on?
* Clean React code, correct separation of concern for the props & states.
* Stay hydrated 💧 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-21 15:45 UTC, LenaNguyen reviewed
padding for the rows is a little off 
![image](https://user-images.githubusercontent.com/43686735/159297683-8aa0c686-aab5-4d6b-8529-00d11ffc1acb.png)

I'm pretty sure the horizontal padding should be equal so let's use 47px. 
Since the Td elements have their own padding and it would be annoying to remove their padding each time, just add some extra padding to `tr`. i.e. px="20px", py="2.5px"

2022-03-21 15:48 UTC, LenaNguyen reviewed
Also for UI changes can you pls add a demo on the default page or something next time 🙏 my docker takes a million years to start so sometimes it's much faster to use the firebase preview. The downside is you'd have to remove it after get another approval tho.

2022-03-22 17:39 UTC, LenaNguyen commented
> padding for the rows is a little off ![image](https://user-images.githubusercontent.com/43686735/159297683-8aa0c686-aab5-4d6b-8529-00d11ffc1acb.png)
> 
> I'm pretty sure the horizontal padding should be equal so let's use 47px. Since the Td elements have their own padding and it would be annoying to remove their padding each time, just add some extra padding to `tr`. i.e. px="20px", py="2.5px"

Actually idk if this is that important @sherryhli . If we change the theme to accommodate for this padding then other places where we use a `Tr` but isn't formatted like this will need to be changed.  The default spacing from Chakra also looks fine.

2022-03-22 23:06 UTC, sherryhli requested changes
Nice! 🔥 Some small code improvement suggestions and a minor UI deviation, LGTM otherwise!

2022-03-22 23:06 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
> +          <Button color="text.critical" variant="none">
Hmm I'm seeing different y-paddings between the 3 types of rows, they should equal according to the designs

![image](https://user-images.githubusercontent.com/30205929/159590538-0be69fe6-f20d-4c7b-8916-480d13618482.png)

2022-03-22 23:09 UTC, sherryhli commented
> > padding for the rows is a little off ![image](https://user-images.githubusercontent.com/43686735/159297683-8aa0c686-aab5-4d6b-8529-00d11ffc1acb.png)
> > I'm pretty sure the horizontal padding should be equal so let's use 47px. Since the Td elements have their own padding and it would be annoying to remove their padding each time, just add some extra padding to `tr`. i.e. px="20px", py="2.5px"
> 
> Actually idk if this is that important @sherryhli . If we change the theme to accommodate for this padding then other places where we use a `Tr` but isn't formatted like this will need to be changed. The default spacing from Chakra also looks fine.

@LenaNguyen Yeah I'm for staying consistent to a single theme variant if possible, could we check with design to see if this small deviation is okay?

2022-03-23 04:27 UTC, sherryhli commented
Just realized something: with the way we plan on fetching data for the schedule creation frontend (running a query on the signups table rather than shifts), we wouldn't know about any shifts without signups. That means the row type below would not be seen, and the shift would also not be shown as a dot in the calendar.

![row](https://camo.githubusercontent.com/c0852d2f64ffaa20ef777fff2b71b21b520a7344fced181e0e2f3d4f1909d7cd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631346661343532383439663838323566663465656134332f30383961396231652d396461372d343737362d613062302d336366396139666238346263)

cc @JoshuaYe @LenaNguyen Do you have any input on the necessity and priority of this feature? How useful is it to view shifts that do not have any signups in schedule creation?

(@lambo-liu no change needed for now, please keep this row type in the code)

2022-03-24 15:54 UTC, LenaNguyen commented
> Just realized something: with the way we plan on fetching data for the schedule creation frontend (running a query on the signups table rather than shifts), we wouldn't know about any shifts without signups. That means the row type below would not be seen, and the shift would also not be shown as a dot in the calendar.
> 
> ![row](https://camo.githubusercontent.com/c0852d2f64ffaa20ef777fff2b71b21b520a7344fced181e0e2f3d4f1909d7cd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631346661343532383439663838323566663465656134332f30383961396231652d396461372d343737362d613062302d336366396139666238346263)
> 
> cc @JoshuaYe @LenaNguyen Do you have any input on the necessity and priority of this feature? How useful is it to view shifts that do not have any signups in schedule creation?
> 
> (@lambo-liu no change needed for now, please keep this row type in the code)

It seems useful to know that there are some shifts that no one is registered for in the overview

2022-03-31 22:52 UTC, lambo-liu commented on frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
> +          <Button color="text.critical" variant="none">
Thanks for catching this 👍

2022-04-01 00:23 UTC, LenaNguyen approved these changes
LGTM! 
![](https://media.giphy.com/media/Fkmgse8OMKn9C/giphy.gif)

2022-04-01 04:08 UTC, sherryhli approved these changes

2022-04-01 04:23 UTC, merged