Implement monthly view calendar for admin scheduling UI
uwblueprint/sistering pull request #207
Opened 2022-03-13 06:32 UTC by lambo-liu

## Ticket link

Closes #177 

## Implementation description
* Implemented the monthly view calendar for the admin schedule UI.
* Used the FullCalendar daygrid library add-on

## Steps to test
1. Install new dependencies and start frontend
2. Add the following snippet to `Default.tsx`, importing components/variables when necessary:
```
<Container maxW="container.xl">
    <AdminShiftCalendar events={ADMIN_SHIFT_CALENDAR_TEST_EVENTS} />
</Container>
```
3. Check that the events are displayed appropriately. Days with no events should be greyed out. "Unsaved" events have red dots and "saved" events have green dots.
4. Feel free to change the test case, as long as all events of `ADMIN_SHIFT_CALENDAR_TEST_EVENTS` are in the same month.

## What should reviewers focus on?
* Clean UI, expected behaviour & styling 🖌️ 🌈 
* <ins>**_I have defeated FullCalendar's final boss._**</ins>

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-20 17:35 UTC, sherryhli requested changes
✨ Looks amazing! ✨

Nothing too big from me, just some questions and suggestions :)

2022-03-20 17:35 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +import React from "react";
What do you think about putting this component under the `admin/ShiftCalendar` folder instead? I think the component is fairly generic and not specific to scheduling in any way

Suggested renaming:
`AdminShiftCalendar` -> `MonthViewReadOnlyShiftCalendar`
`ShiftCalendar` -> `WeekViewShiftCalendar`

2022-03-20 17:35 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminShiftCalendar.css
> +
Styling of the header row doesn't quite match the designs

Current implementation:
![image](https://user-images.githubusercontent.com/30205929/159174554-ac525fca-9f16-4369-a998-8efbafe14a78.png)

Designs:
![image](https://user-images.githubusercontent.com/30205929/159174580-f9c7e6f5-0cf5-4622-9736-c71664b6f477.png)

2022-03-20 17:35 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +};
Let's move to the new `CalendarTypes.ts` file as well

2022-03-20 17:35 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +        initialDate={events.length > 0 ? events[0].start : new Date()}
Does it matter if `events[0]` is not chronologically the first in the month?

2022-03-20 17:35 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +        initialDate={events.length > 0 ? events[0].start : new Date()}
Something I discovered from the shift calendar is that FullCalendar does not re-render when `initialDate` changes. Can you confirm if the `initialDate` is updated when a new set of events is passed as props?

https://github.com/uwblueprint/sistering/pull/203#discussion_r826384289

2022-03-24 21:52 UTC, lambo-liu commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +import React from "react";
Yeah, I like that idea.

2022-03-24 21:57 UTC, lambo-liu commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +import React from "react";
Since both of the calendar share common styles, I'll merge the css into one file `Calendar.css`.

2022-03-24 22:18 UTC, lambo-liu commented on frontend/src/components/admin/schedule/AdminShiftCalendar.css
> +
Yeah, I asked Krystal about this and we decided to keep the monthly calendar header styling consistent with the weekly calendar view. I think we can keep the current implementation.

2022-03-24 22:19 UTC, lambo-liu commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +        initialDate={events.length > 0 ? events[0].start : new Date()}
I don't think so? I think the initialDate is just there to tell the calendar which month to display. As long as all of the events passed in are of a single month, this should be fine.

2022-03-24 22:22 UTC, lambo-liu commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +        initialDate={events.length > 0 ? events[0].start : new Date()}
Not quite sure how to test this without integrating the calendar into the header. I think maybe we can investigate into this in the calendar header ticket (where the events are being passed in).

What I suspect though, is that FullCalendar is not refreshing when the events props change. We might be able to get around this using a force refetch - https://fullcalendar.io/docs/Calendar-refetchEvents.

2022-03-24 22:28 UTC, lambo-liu commented
I left the Calendar component in Default.tsx so that you can take a look again when you review. I'll remove it once this PR is approved!

2022-03-25 04:55 UTC, sherryhli commented on frontend/src/components/admin/schedule/AdminShiftCalendar.tsx
> +        initialDate={events.length > 0 ? events[0].start : new Date()}
Sounds good 👍

Was thinking of making wrapper like the one described in https://github.com/fullcalendar/fullcalendar/issues/4684#issuecomment-620787260 for the week view calendar, would be applicable here too.

2022-03-25 04:57 UTC, sherryhli reviewed
LGTM, will approve after addressing tiny lint issue

2022-03-25 04:57 UTC, sherryhli commented on frontend/src/types/CalendarTypes.ts
> +};
Nit: newline please

2022-03-31 22:33 UTC, sherryhli approved these changes
🚢🚢🚢

2022-03-31 23:01 UTC, merged