Rickson/volunteer select availability table datafetch newpage
uwblueprint/sistering pull request #210
Opened 2022-03-13 21:33 UTC by MatoPlus

## Ticket link

Closes #129 

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-18 01:26 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
@LenaNguyen do we have a ticket somewhere to make a shifts query with a filter arg? I can take on it.

2022-03-18 01:27 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
Same query as in volunteer posting details page. Should we put these in a dedicated folder for FE graphql queries?

2022-03-18 01:28 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +    return <Spinner />;
This is a very primitive loading component, it might be benefitable to create a proper loading component. Can be something simple like a centered purple.50 spinner

2022-03-18 01:29 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +  const [selectedShifts, setSelectedShifts] = useState<ShiftDTO[]>([]);
I'm using the ShiftDTO for now but we probably need another type with some note type. I can do this in my ticket if there isn't another ticket for it.

2022-03-18 01:30 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +                          setSelectedShifts={setSelectedShifts}
Not a super big fan of drilling but we have to deal with it if we choose to go w/o state management

2022-03-21 14:15 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
sure! we could start a `/graphql` folder in the frontend (feel free to call it something better)

2022-03-21 14:25 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +  const [selectedShifts, setSelectedShifts] = useState<ShiftDTO[]>([]);
Nope no ticket for this. Since this type is specific to the ui, maybe add it a new file called availabilitiesTypes.tsx in `frontend\src\types`

2022-03-21 14:32 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
you can also just add it in this pr if that's easier tbh

2022-03-21 14:32 UTC, LenaNguyen requested changes
Just the changes you pointed out! Remember to persist notes when you add the new type :)

2022-03-21 14:36 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +            console.log(selectedShifts);
Created #230 for the mutation call

2022-03-25 01:09 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
Would it make sense to put it in the existing /backend/graphql/index.ts file?

2022-03-25 01:17 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
I think with the current way we're calling graphql, it doesn't really makes sense to put "constant queries" into their own files, I think these queries are written to be component/page specific.

There's a lot of gql queries scattered in components atm, and I don't really wanna make things inconsistent 😅

2022-03-25 02:29 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +  const [selectedShifts, setSelectedShifts] = useState<ShiftDTO[]>([]);
hmm I think it might make sense to create `SignupTypes.ts` in `types/api/` instead?

2022-03-25 03:31 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
This is done!

2022-03-25 03:31 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTable.tsx
> +                          setSelectedShifts={setSelectedShifts}
This got even worst with notes, pretty ugly :(

2022-03-28 01:34 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +`;
We actually want to fetch shifts and their corresponding shift signups for the given user so that if they previously have inputted their availability, it shows on the table. 

#162 This endpoint is being worked on so we can keep it the way it is for now!

2022-03-28 01:55 UTC, LenaNguyen approved these changes
Made a ticket to change the fetch ones the endpoint is made #242

![](https://media.giphy.com/media/cL4pqu8GGRIihabgSM/giphy.gif)

2022-03-28 17:35 UTC, merged