Modal for removing volunteers
uwblueprint/sistering pull request #222
Opened 2022-03-19 18:28 UTC by hujoseph99

## Ticket link

Closes #159

## Implementation description
* Created a modal for removing volunteers.

## Steps to test
1. Open the app
2. Go to Remove Volunteer Demo in menu bar
3. Enter a name of a volunteer you would like to remove
4. Verify that the modal works and looks as expected

## What should reviewers focus on?
* Styling of the modal matches mockup

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-19 18:29 UTC, hujoseph99 commented on frontend/src/components/admin/RemoveVolunteerModal.tsx
> +import {
This file is the heart of the changes. All other changes are just for demo purposes and can be later removed.

2022-03-21 14:52 UTC, LenaNguyen requested changes
just a couple styling things!

2022-03-25 21:37 UTC, hujoseph99 commented on frontend/src/components/admin/RemoveVolunteerModal.tsx
> +        </ModalBody>
Fixed!

2022-03-25 21:37 UTC, hujoseph99 commented on frontend/src/components/admin/RemoveVolunteerModal.tsx
> +        </ModalHeader>
Fixed!

2022-03-25 21:37 UTC, hujoseph99 commented on frontend/src/components/admin/RemoveVolunteerModal.tsx
> +import {
Fixed!

2022-03-25 21:38 UTC, hujoseph99 commented on frontend/src/components/admin/RemoveVolunteerModal.tsx
> +      <ModalContent borderRadius={8} pt={3} pl={3} pr={3} pb={2}>
Fixed!

2022-03-28 12:16 UTC, LenaNguyen submitted a review, later dismissed
![](https://media.giphy.com/media/37R3fbYQpWQ7m2WOsF/giphy.gif)

2022-03-29 17:16 UTC, LenaNguyen requested changes

2022-03-29 17:16 UTC, LenaNguyen commented on frontend/src/components/pages/Default.tsx
> +        />
"create shifts" and "review posting" may have been added in from the rebase. Can you remove all of these (including the demo)? They're not needed in main.

2022-03-29 17:35 UTC, hujoseph99 commented on frontend/src/constants/Routes.ts
> +export const REMOVE_VOLUNTEER_MODAL_DEMO = "/remove_volunteer_demo";
Do you want me to remove the full demo?

2022-03-31 23:02 UTC, hujoseph99 commented on frontend/src/constants/Routes.ts
> +export const REMOVE_VOLUNTEER_MODAL_DEMO = "/remove_volunteer_demo";
Removed

2022-03-31 23:02 UTC, LenaNguyen approved these changes

2022-03-31 23:02 UTC, hujoseph99 commented on frontend/src/components/pages/Default.tsx
> +        />
Removed

2022-03-31 23:06 UTC, merged