Create Rich Text Display Component
uwblueprint/sistering pull request #224
Opened 2022-03-20 06:45 UTC by Boyazhang1

## Ticket link

Closes #130 

## Implementation description
* Created a rich text display component to be used in admin "review and "post"
<img width="1057" alt="Screen Shot 2022-03-19 at 11 42 08 PM" src="https://user-images.githubusercontent.com/82241706/159151352-9515931b-0619-4cdd-93e3-b89e35f513ed.png">

## Steps to test
1. Seed the database (run "docker exec -it sistering_backend bash -c "npx prisma db seed")
2. Uncomment the "for testing" code in CreatePostingReview.tsx to fetch a sample richText string from the seed data 
3. Set the child of the RichTextDisplay component used on line 82 of CreatePostingReview.tsx to richTextDescription
4. Navigate to http://localhost:3000/admin/posting/create/review to see the richText displayed 

Note: 
The 2 sample richText strings from the seed data are unstyled, so I'm not sure whether styled richText will format properly  

## What should reviewers focus on?
* RichTextDisplay component works
* Testing method is correct (I feel like there might be a better way to fetch the descriptions from the db)
* How to test with a richText string that is styled? 

## Checklist
- [ x] My PR name is descriptive and in imperative tense
- [ x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [x ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-23 06:10 UTC, sherryhli requested changes
Very cool 😎

There are a couple of lint warnings, please:
1. Remove any unused imports
2. Run `yarn fix` in the frontend folder
3. Remove the rich text test data before merging

Please also install the [draft-js types package](https://www.npmjs.com/package/@types/draft-js) and commit the updated package.json and yarn.lock files
```bash
# if you have yarn locally
cd frontend
yarn add @types/draft-js --dev

# otherwise
docker exec -it sistering_frontend /bin/bash -c "yarn add @types/draft-js --dev"
```

2022-03-24 02:24 UTC, Boyazhang1 commented on frontend/src/components/admin/posting/RichTextDisplay.tsx
> +      <Editor editorState={editorState} readOnly onChange={() => {}} />
Yep it is a required prop: https://draftjs.org/docs/api-reference-editor/#onchange

2022-03-24 02:33 UTC, Boyazhang1 commented on frontend/src/components/admin/posting/RichTextDisplay.tsx
> +    }
good question, hmm I guess if the children is falsey, the editorState would just take on the default state which is empty already (EditorState.createEmpty()), so there is no need to set it to empty again ?

2022-03-24 16:07 UTC, sherryhli requested changes
Just one last thing! I also see some lint warnings so please run `yarn fix` again 🙂

2022-03-24 16:07 UTC, sherryhli commented on frontend/src/components/common/RichText/RichTextDisplay.tsx
> +    }
Let's make this part a little more robust, addressing the general case of `children` being an invalid JSON string. Note that we don't have a standardized method for logging frontend errors at the moment, so we'll just use `console.log` for now.

```ts
try {
  const contentState: RawDraftContentState = JSON.parse(children);
  setEditorState(
    EditorState.createWithContent(convertFromRaw(contentState)),
  );
} catch (e: SyntaxError) {
  /* eslint-disable-next-line no-console */
  console.log(`Invalid content state ${children} passed to RichTextDisplay`);
  setEditorState(EditorState.createEmpty());
}
```

2022-03-24 16:08 UTC, sherryhli commented on frontend/src/components/admin/posting/RichTextDisplay.tsx
> +    }
Please see new suggestion: https://github.com/uwblueprint/sistering/pull/224#discussion_r834478758

2022-03-25 00:34 UTC, Boyazhang1 commented on frontend/src/components/common/RichText/RichTextDisplay.tsx
> +    }
Sounds good, it works as expected. I had to change the SyntaxError type to unknown due to the error "Catch clause variable type annotation must be 'any' or 'unknown' if specified".

Error: 
<img width="638" alt="Screen Shot 2022-03-24 at 5 28 50 PM" src="https://user-images.githubusercontent.com/82241706/160031723-b48fe21b-7c17-4e64-9e1f-69b4a3586d5e.png">

2022-03-25 02:39 UTC, sherryhli reviewed
Small nit

2022-03-25 02:39 UTC, sherryhli commented on frontend/src/components/common/RichText/RichTextDisplay.tsx
> +    if (children) {
This check shouldn't be needed anymore, a falsey `children` prop will cause `JSON.parse()` to throw so the catch block will handle it

2022-03-26 00:03 UTC, merged