Jiaru/shifts table row
uwblueprint/sistering pull request #225
Opened 2022-03-20 17:32 UTC by jiarucao

## Ticket link
Closes #122 and #121 

## Implementation description
* Created `VolunteerShiftsTableRow`, `VolunteerShiftsTable` and `VolunteerShiftsTableDate` to display volunteer shifts
* Added theme variants to the `Link` and `Table` components

## Steps to test
(Note: mock data is hardcoded right now under `VolunteerShiftsPage`)
1. Navigate to `/volunteer/shifts` on http://localhost:3000/ 
2. Verify that table data is rendered correctly for the two variations of table data 
3. In the `VolunteerShiftsPage` component, edit the `shifts` prop for `VolunteerShiftsTable` to be empty array. Verify that the empty state for the table component is rendered correctly. 

## What should reviewers focus on?
* Correct behaviour for the table 
* Code logic

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-23 05:39 UTC, sherryhli requested changes
Nice work so far!

Tagging @lambo-liu @MatoPlus for a review as they've also worked on table components

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
> +          {day.shifts.length > 0
I believe it should be safe to expect this condition to always be true (we'll be fetching data using a `ShiftSignups` query which will not return dates without signups). Let me know if I'm mistaken though :)

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
> +    date: new Date("2022-01-21T00:00:00+00:00"),
Note to self (no action needed @jiarucao): dates are becoming a real mess 😩. We should standardize on when we use `Date` objects vs string representations in the frontend. This may become more clear once data fetching is done (dates and datetimes in GraphQL responses are always strings in `YYYY-MM-DD` or `YYYY-MM-DDTHH:mm` formats).

cc @LenaNguyen

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTable.tsx
> +  Button as ChakraButton,
Probably don't need to alias, just `Button` is fine :)

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/theme/index.ts
> +              borderCollapse: "collapse",
Let's add `backgroundColor: "background.white"`

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
> +          backgroundColor="background.white"
See suggestion to add background colour to table theme

```suggestion
```

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
> +      <Box bg="background.light" p={10}>
Small bug: background colour is not covering entire screen. Just an FYI, not in scope for this ticket :)

![image](https://user-images.githubusercontent.com/30205929/159630269-ca564840-d897-4fd9-9338-86bc2a9383d1.png)

2022-03-23 05:39 UTC, sherryhli commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
> +          <Text>{time + duration}</Text>
Missing space

```suggestion
          <Text>{time + " " + duration}</Text>
```

2022-04-03 15:55 UTC, jiarucao commented on frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
> +          backgroundColor="background.white"
This is still needed for the empty table / no shifts case :)

2022-04-03 20:31 UTC, sherryhli requested changes
Last little thing!

2022-04-03 20:31 UTC, sherryhli commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
> +      )}
Small nit but I would prefer changing this to 2 ternary statements instead to make it clear that exactly 2 columns are displayed

2022-04-05 03:48 UTC, jiarucao commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
> +      )}
The shift time and deadline aren't in the same column, so I'd have to repeat the posting name element inside the ternary statement. Do we mind that repetition? 
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/49663161/161674960-3e873e4e-e71f-4aba-86ee-5e062c9b30fe.png">

2022-04-05 16:08 UTC, sherryhli commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
> +      )}
Personally fine with trading a little bit of code repetition for more readability :)

2022-04-06 02:21 UTC, jiarucao commented on frontend/src/components/volunteer/shifts/VolunteerShiftsTableRow.tsx
> +      )}
updated!

2022-04-07 20:02 UTC, sherryhli approved these changes
LGTM! 🚢

2022-04-07 21:53 UTC, merged