Add Rich Text Field for Create Posting Basic Info
uwblueprint/sistering pull request #238
Opened 2022-03-27 00:02 UTC by albertlai431

## Ticket link

Closes #191 

## Implementation description
* Created RichTextField component with support for different font sizes, inline formatting (bold, italics, and underline), and block formatting (ordered and unordered lists)
* Replaced Textarea component with RichTextField component in the CreatePostingBasicInfo component

![image](https://user-images.githubusercontent.com/44041989/160260970-f6d0c7ef-8f72-4137-b744-ffa139e57da2.png)

Error State:
![image](https://user-images.githubusercontent.com/44041989/160260980-f4e08cbc-9e44-4ea9-8876-4314aed4a866.png)

## Steps to test
1. `docker-compose up --build`
2. http://localhost:3000/admin/posting/create/basic-info
3. Test out buttons for the different formatting styles and font sizes
4. Test out keyboard shortcuts for the different formatting styles (i.e., bold is Ctrl-B on Windows / Cmd-B on macOS)
5. Test out error states

## What should reviewers focus on?
* Ensuring the rich text formatting style and font size controls are functioning as expected
* Random edge cases that might break the editor

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-03-29 18:37 UTC, LenaNguyen requested changes
This is really cool! Great work on it!

Can we easily handle/fix these scenarios?

1. Start writing in a font other than body. For example H1. Click enter to make a new line. Type "- " to start an unordered list. The selector says the font is Heading when it's actually Body. Same with ordered list.

2. Show an active state for the bold, italic, and underline buttons when the selected text has those stylings. Maybe using [this](https://stackoverflow.com/questions/48906838/is-there-any-way-to-get-the-style-under-cusor-in-draft-js) ?

1 seems like a bug but 2 is just an extra thing that does not have to be done in this ticket.

2022-03-29 18:37 UTC, LenaNguyen commented on frontend/src/components/common/RichTextField.tsx
> +  //             pass the previous description into initialContent
Move into a block comment like this

```suggestion
  /*
  content in the stringified form of a ContentState (i.e. derived from using RichTextField)
  this should not be reactive! (not updated onChange)
  how to use: for editing pre-existing content (e.g. on editing a requestGroup's description),
  pass the previous description into initialContent
  */
  initialContent: string; 
```

2022-04-01 00:04 UTC, LenaNguyen submitted a review, later dismissed
Thank you for blessing the codebase with this richtext editor 🙏 

![](https://media.giphy.com/media/xTk9ZZRGWEelhRiEak/giphy.gif)

2022-04-01 14:55 UTC, albertlai431 commented
@LenaNguyen had to resolve some diffs w/ `main`, could you approve again? Thanks!

2022-04-01 15:18 UTC, LenaNguyen approved these changes

2022-04-01 18:09 UTC, merged