Edit volunteers shift time header
uwblueprint/sistering pull request #251
Opened 2022-04-01 00:42 UTC by briantu

## Ticket link

Closes #173 

## Implementation description
* Created `ShiftTimeHeader.tsx` component in `frontend\src\components\admin\schedule`
* The header accepts two props:
  *  Array of shift times
  * `onDateSelected` function called when select option is changed

## Steps to test
1. Go to `/volunteer/shifts` where the component is temporarily mounted on
2. The `onDateSelected` method currently just console logs the selected value. Check that the correct values are being logged.

## What should reviewers focus on?
* Code correctness
* Component follows designs

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-01 01:01 UTC, LenaNguyen requested changes
i should have thought this one through more 🙃

2022-04-01 01:01 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
> +        dateTimes={["5:00pm - 7:00pm", "7:00pm - 9:00pm", "9:00pm - 12:00am"]}
hmmm my bad now that I think about it, this should actually take an array of `shifts`  with the structure
```
shifts = [
  {
    shiftId: <ID>
    shiftStartTime: Date (e.g. Date(2022-04-11T13:30))
    shiftEndTime: Date 
  }
]
```

and then instead of onDateSelected, we want onShiftSelected which accepts the shiftId. 

This is because 1) the selector should be in charge of formatting the date objects from the api into the appropriate string representation and 2) we are using this selector to choose which shift to display signups for 

sorry for the confusion!

To format a date into the time, you can use `formatTimeHourMinutes` in `frontend\src\utils\DateTimeUtils.ts`

2022-04-02 23:25 UTC, briantu commented on frontend/src/components/pages/volunteer/shift/VolunteerShiftsPage.tsx
> +        dateTimes={["5:00pm - 7:00pm", "7:00pm - 9:00pm", "9:00pm - 12:00am"]}
No problem! Is it okay that I have that shift type defined in the component's file, or should I put it in one of the types files?

2022-04-03 20:02 UTC, LenaNguyen requested changes
Thanks for incorporating the changes! Remove demo pls

![](https://media.giphy.com/media/f6VfCFyOL5KmiICskp/giphy.gif)

2022-04-03 20:29 UTC, LenaNguyen approved these changes

2022-04-03 20:33 UTC, merged