Add submit signups mutation to availability page
uwblueprint/sistering pull request #253
Opened 2022-04-01 02:27 UTC by MatoPlus

## Ticket link

Closes #230 

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-03 23:25 UTC, MatoPlus commented on backend/graphql/index.ts
> +      isAuthorizedForCreateShiftSignups("userId") &&
@uwblueprint/sistering-w22-pls can I get a confirmation that this check is right? I assume to delete, you need perm to create + update (counts as delete as well)

2022-04-03 23:36 UTC, MatoPlus commented on backend/services/implementations/shiftSignupService.ts
> +        ),
In order to make this code robust, I don't think I can do this query in one `prisma.x.update` call. main reason being that to do so, we need to ensure that userId is the same for all shiftsign ups, I don't think there's really any guarantee that they have the same userId, so this can be used a general backend query for combining delete +upserts

I think this is a bit more readable as well since it's just subsequent calls in a tcx

2022-04-03 23:36 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +                  deleteShiftSignups: [],
This part isn't trivial, i feel like our client types isn't super clean atm.

2022-04-14 22:17 UTC, LenaNguyen commented on backend/graphql/index.ts
> +      isAuthorizedForCreateShiftSignups("userId") &&
isAuthorizedForUpdateShiftSignups should be enough because it already includes the same permissions as the createShiftSignups.

Basically you can only create a signup if you're a volunteer and your userId matches the userId of the signups.

You can update a singup if you match the above OR if you're an admin (so we can update the shift status)

2022-04-15 00:42 UTC, MatoPlus commented on backend/services/implementations/shiftSignupService.ts
> +      });
Since we're using a mixed transaction of different ops, I don't think we get a clean response from prisma, this is wrong. with empty response, I got something like `[ { count: 0 } ]`. I'm investigating options.

2022-04-15 00:55 UTC, MatoPlus commented on backend/services/implementations/shiftSignupService.ts
> +                userId: Number(deleteShiftSignup.userId),
100%. Good catch. I'll change the predicate to search for all conjugations of shiftid/userid that makes up the pid for signups.

2022-04-15 03:58 UTC, LenaNguyen reviewed
nvm 😅

2022-04-15 04:27 UTC, LenaNguyen submitted a review, later dismissed
It's working great! Just a couple comments

2022-04-15 04:27 UTC, LenaNguyen commented on backend/graphql/index.ts
> +    upsertDeleteShiftSignups: isAuthorizedForUpdateShiftSignups("userId"),
Looking at this again, we will actually need a custom authorization method similar to `isAuthorizedForCreateShiftSignups`. Currently this endpoint should only be accessible to volunteers. We would need to loop through each shift in  upsertShiftSignups and DeleteShiftSignups and check that the userID matches the userID of the accessToken.

This can be done in a different ticket. For now let's just use `authorizedByAdminAndVolunteer` to make testing easy.

2022-04-15 04:27 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +import { gql, useMutation, useQuery } from "@apollo/client";
can you remove the frontend changes from this pr? let's just keep it to backend to match the scope of the ticket.

2022-04-15 04:27 UTC, LenaNguyen commented on backend/services/implementations/shiftSignupService.ts
> +    upsertDeleteShiftSignups: UpsertDeleteShiftSignupsRequestDTO,
can the param just be deleteShiftSignups and upsertShiftSignups instead of putting them in an object?

2022-04-17 19:28 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +import { gql, useMutation, useQuery } from "@apollo/client";
for sure, I'll keep the revert commit in the merge for reference

2022-04-21 16:09 UTC, LenaNguyen requested changes
LGTM! Just run `yarn fix` for the linting warning

2022-04-21 16:10 UTC, LenaNguyen reviewed
TO DO: remove createShiftSignup and updateShiftSignup

2022-04-21 22:21 UTC, LenaNguyen approved these changes
![](https://media.giphy.com/media/12OTxgtyHG11QI/giphy.gif)

2022-04-21 23:04 UTC, merged