DRAFT: Schedule Review Table Data Fetch
uwblueprint/sistering pull request #259
Opened 2022-04-02 20:50 UTC by hujoseph99

## Ticket link

Closes #162 

**This is a draft PR, still have to add in frontend portion for data fetch**

## Implementation description
* Created new endpoint `shiftsWithSignupsAndVolunteersByPosting`
* This is a draft PR, still have to add the front end data-fetching 

## Steps to test
1. Populate database as in this #90 
2. Add skills and branches for the user with the following queries: `
  * `insert into skills values (1, "test skill");`
  * `insert into branches values (1, "test branch");`
  * insert into "_SkillToVolunteer" values (1, 1);`
  * insert into  "_BranchToVolunteer" values (1, 1);`
3. Test the query to see if it works as expected

## What should reviewers focus on?
* This is draft PR, currently just focus on if backend API works as expected. The frontend portion will be added to this ticket later.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-03 22:06 UTC, LenaNguyen requested changes
looking good, the main changes have to do with 1) removing skills + branches from the response and 2) add another `where` filter to the prisma query for `userId` and `signupStatus`

2022-04-03 22:06 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +              ) {
you don't need this if statement if you add filtering on signups to the prisma call right?

2022-04-03 22:06 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +                );
No action needed on this pr but we should probably store user emails in the db so we don't have to make a call to firebase every time. We'll do this in the future!

2022-04-03 22:06 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +                  .getUser(signup.user.authId);
To make this a bit faster, if `userId != null` then we only need to fetch the user email once since all signups will be for the same user.

2022-04-03 22:06 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +          shift.signups.map(async (signup: SignupWithVolunteers) => {
Do you need two `Promise.all` ? Not sure if this works but can you do `await shift.signups.map(...)` inside the first promise.all?

2022-04-03 22:56 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +            include: {
It actually isn't possible to do this in prisma as far as I understand because `signups` is a list. The closest equivalent prisma has is `has`, but that only works on scalar lists.

2022-04-03 22:57 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +              ) {
Correct, but I don't think this type of filtering exists in Prisma? I could be wrong though

2022-04-03 23:00 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +          shift.signups.map(async (signup: SignupWithVolunteers) => {
I tried to remove the inner one initially, but it doesn't work because the `await` is container within the inner map. I just realized that I might be able to remove the outer `Promise.all` though. Let me try it out!

2022-04-08 00:25 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +                      skills: true,
Removed

2022-04-08 00:39 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +            include: {
hmm could you use [every](https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#relation-filters)?

2022-04-13 01:42 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +            include: {
I've tested it and it unfortunately does not work. I believe it only matches shift signups where **every** volunteer in the array matched our filters. So, if we're filtering by userId and a posting has signups with two different userIds, it just won't return that posting since not every element in the array has matched our filters.

2022-04-13 01:49 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +        skills: convertToSkillResponseDTO(signup.user.volunteer.skills),
Removed

2022-04-13 01:50 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +                  .getUser(signup.user.authId);
As discussed, we removed emails from the response in this endpoint

2022-04-15 05:14 UTC, LenaNguyen requested changes

2022-04-15 05:14 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +            include: {
I tried 

```suggestion
        include: {
          signups: {
             where: {
              userId: userId === undefined ? userId : Number(userId),
              status: signupStatus ?? undefined,
            },
            include: {
```
and removed the filter we do after. It seems to work for me. Can you try it out?

2022-04-21 18:04 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +            include: {
Testing for getShiftsWithSignupAndVolunteerForPosting :

1. Go to backend\graphql\index.ts. On line 200 - 201, change the auth for createShiftSignups and updateShiftSignup to be authorizedByAdminAndVolunteer() to make testing easier.

2. Create a new user

3. Go into the db and update the user role to be volunteer + insert a new volunteer:
`update users set role = 'VOLUNTEER' where id = 4;`
`insert into volunteers(id, hire_date, date_of_birth, pronouns) values(4, '2022-04-17 19:41:55.55', '2000-08-19 23:15:30', 'they/them');`

Create shift signups for both volunteers:
```
mutation CreateShiftSignups{
  createShiftSignups(
    shifts: [ { shiftId: "5", userId: "4", numVolunteers: 3, note: "test" }, { shiftId: "2", userId: "4", numVolunteers: 3, note: "test" }, { shiftId: "2", userId: "2", numVolunteers: 3, note: "test" }, { shiftId: "1", userId: "2", numVolunteers: 3, note: "test" }]
  ) {
    shiftId
    userId
    numVolunteers
    note
  }
}
```

4. Update at least one shift signup to have a status other than pending:
```
mutation UpdateShiftSignup{
  updateShiftSignup(
    shiftId: "1"
    userId: "2"
    update: { status: CONFIRMED, note: "test", numVolunteers: 3 }
  ) {
    shiftId
    userId
    numVolunteers
    note
    status
  }
}
```

5. Query for shifts with signups and volunteers using various filter combinations (e.g. just posting id, posting id  + user id, posting id + user id + signup status)
```
query ShiftsWithSignupVolunteers {
  shiftsWithSignupsAndVolunteersByPosting(postingId:1, userId: 4, signupStatus:PENDING) {
    id
    postingId
    startTime
    endTime
    signups {
      status
      shiftId
      userId
    }
  }
}
```

2022-04-21 22:52 UTC, hujoseph99 commented on backend/services/implementations/shiftService.ts
> +            include: {
This seems to work! I've made the changes and gone with this approach now. Thanks for the testing :)

2022-04-22 00:11 UTC, LenaNguyen commented on frontend/src/types/api/UserType.ts
> +  email: string;
remove email since we're not returning it anymore

2022-04-22 00:37 UTC, hujoseph99 commented on frontend/src/types/api/UserType.ts
> +  email: string;
removed

2022-04-22 02:47 UTC, LenaNguyen approved these changes
Thanks for incorporating all the changes! So glad to have this merged in :))

![](https://media.giphy.com/media/sVnKj2wDhUTsFKFWhx/giphy.gif)

2022-04-22 02:48 UTC, merged