Augment Employee Model
uwblueprint/sistering pull request #263
Opened 2022-04-09 02:10 UTC by Boyazhang1

## Ticket link

Closes #245 

## Implementation description
* Augmented Employee model with title field, and relevant backend methods to read/write this field

## Steps to test
1.  not too sure how to test? 

## What should reviewers focus on?
*  the modified backend methods are able to correctly read/write the title field

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-10 03:32 UTC, sherryhli requested changes
Almost there! Two things:
1. Please select the `title` field in the `employeeUsers` query located in the `CreatePostingBasicInfo` component: https://github.com/uwblueprint/sistering/blob/main/frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx#L65
2. Please test your changes as suggested in Discord, thanks!

2022-04-10 03:32 UTC, sherryhli commented on frontend/src/components/admin/posting/CreatePostingReview.tsx
> +                    { firstName, lastName, email, phoneNumber, title: title1 },
```suggestion
                    { firstName, lastName, email, phoneNumber, title: employeeTitle },
```

2022-04-10 19:36 UTC, Boyazhang1 commented
> Almost there! Two things:
> 
> 1. Please select the `title` field in the `employeeUsers` query located in the `CreatePostingBasicInfo` component: https://github.com/uwblueprint/sistering/blob/main/frontend/src/components/admin/posting/CreatePostingBasicInfo.tsx#L65
> 2. Please test your changes as suggested in Discord, thanks!

Thanks for the guidance! I modified the "Steps to Test" section of this ticket

2022-04-15 18:23 UTC, sherryhli requested changes
Minor thing and then good to ship!

2022-04-15 18:23 UTC, sherryhli commented on backend/graphql/types/userType.ts
> +    title: String
Let's make this non-nullable as well
```suggestion
    title: String!
```

2022-04-15 18:23 UTC, sherryhli commented on backend/services/implementations/userService.ts
>          role: user.role,
(Not related to this line, just couldn't add a comment above)

Since you're already in this file, would you mind disabling the eslint warnings for the non-null assertions? They're being used safely in all cases.

Add this above each line causing the warning:
```ts
/* eslint-disable-next-line @typescript-eslint/no-non-null-assertion */
```

2022-04-16 05:05 UTC, sherryhli approved these changes
Awesome, 🚢 it!

2022-04-16 18:10 UTC, merged