Admin Posting Schedule Header
uwblueprint/sistering pull request #266
Opened 2022-04-14 05:02 UTC by hujoseph99

## Ticket link

Closes #179

## Implementation description
* Created the heading according to the mocks

## Steps to test
1. Add the component to `Default.tsx`. For example, I used the following snippet to test: 
```      
<Flex width="100%" justifyContent="center">
  <Box width="90%">
    <AdminPostingScheduleHeader postingName="test" postingID={0} />
  </Box>
</Flex>
```

## What should reviewers focus on?
* Whether the button functionality works as expected
* Whether the component looks like the mocks

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-14 05:03 UTC, hujoseph99 commented on frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
> +          <Button textStyle="button-semibold">Review</Button>
Has the schedule review page been created? If it has, I can add the functionality to navigate to the page here

2022-04-15 01:13 UTC, LenaNguyen commented on frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
> +          <Button textStyle="button-semibold">Review</Button>
No, not yet. If you don't mind, can you add it to this pr? A page called AdminScheduleReviewPage with the route `admin/schedule/posting/:id/review"`

2022-04-15 04:48 UTC, LenaNguyen commented on frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
> +        px="47px"
There shouldn't be any x padding for this component, so that the text and the buttons are aligned with the bottom border.
Designs:
![image](https://user-images.githubusercontent.com/43686735/163519712-685dab97-2d98-4bdd-8aed-bca8b500632c.png)

Current implementation:
![image](https://user-images.githubusercontent.com/43686735/163519803-d6135a17-76eb-4e87-bd1d-17d2e305178e.png)

It looks like the container of this component is the one with the padding.

2022-04-15 04:48 UTC, LenaNguyen requested changes

2022-04-15 04:48 UTC, LenaNguyen commented on frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
> +        px="47px"
There shouldn't be any x padding for this component, so that the text and the buttons are aligned with the bottom border.
Designs:
![image](https://user-images.githubusercontent.com/43686735/163519712-685dab97-2d98-4bdd-8aed-bca8b500632c.png)

Current implementation:
![image](https://user-images.githubusercontent.com/43686735/163519803-d6135a17-76eb-4e87-bd1d-17d2e305178e.png)

It looks like the container of this component is the one with the padding.

2022-04-22 00:49 UTC, hujoseph99 commented on frontend/src/components/admin/schedule/AdminPostingScheduleHeader.tsx
> +        px="47px"
Fixed, I changed it from padding to margins

2022-04-22 02:49 UTC, LenaNguyen approved these changes
![](https://media.giphy.com/media/26tPplGWjN0xLybiU/giphy.gif)

2022-04-22 02:50 UTC, merged