Implement monthly calendar header
uwblueprint/sistering pull request #269
Opened 2022-04-15 03:07 UTC by lambo-liu

## Ticket link

Closes #178 

## Implementation description
* Created a header for the monthly shift calendar that allows navigation between months.
* The header includes the following:
  * Next month button if there are shifts after this month
  * Previous month button if there are shifts before this month
  *Month dropdown to display each month with shifts
* As per discussions with @krystaltruong:
  * The header navigation will start at the earliest event (start date) by default.
  * If there is a month in between with no events, it will still be included in the navigation. (For example, May 2022 in `ADMIN_SHIFT_CALENDAR_TEST_EVENTS` is still displayed). 

## Steps to test
1. Navigate to http://localhost:3000/ to see `ADMIN_SHIFT_CALENDAR_TEST_EVENTS` displayed.

## What should reviewers focus on?
* Potential edge cases?

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-21 22:45 UTC, LenaNguyen reviewed
Why is April 21 purple? This is from the preview link and I tried refreshing 
![image](https://user-images.githubusercontent.com/43686735/164563467-2678052b-6bd3-48ea-959f-5d82f15781b3.png)

2022-04-21 23:06 UTC, lambo-liu commented
> Why is April 21 purple? This is from the preview link and I tried refreshing ![image](https://user-images.githubusercontent.com/43686735/164563467-2678052b-6bd3-48ea-959f-5d82f15781b3.png)

That's today! :)

2022-05-03 05:29 UTC, LenaNguyen requested changes
Looks good! Can you just add this to the AdminSchedulePostingPage and replace the old calendar that's there?

2022-05-04 06:17 UTC, LenaNguyen submitted a review, later dismissed
:shipit:

2022-05-06 02:06 UTC, LenaNguyen approved these changes

2022-05-06 02:06 UTC, merged