Add submit signups volunteer avail client call
uwblueprint/sistering pull request #277
Opened 2022-04-22 00:33 UTC by MatoPlus

## Ticket link

Closes #

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-05-02 05:14 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +// TODO: Check we we need confirmed shift status
I don't think we need to check if the status is CONFIRMED because that happens after the admin creates a schedule. The schedule is after the posting is closed already and volunteers can no longer signup

2022-05-02 06:22 UTC, LenaNguyen requested changes
Just some small changes and it's good to go! 🚀

2022-05-02 06:22 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
>              });
can you move the onClick business logic into a handler? something like `handleSubmitClick`? it'll prevent the business logic from cluttering the UI layout

2022-05-02 06:22 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +            }
Display the error modal. You may need to add a state value

2022-05-02 06:22 UTC, LenaNguyen commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +          onBlur={(event) => {
run `yarn fix`

2022-05-02 06:22 UTC, LenaNguyen commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +      );
```suggestion
      const initDeleteSignups = ((shiftsByPosting as ShiftWithSignupAndVolunteerResponseDTO[]) ?? [])
          .filter((shift) => shift.signups.length > 0)
          .map((shift) => {
            return {
              shiftId: shift.id,
              toDelete: false,
            };
          }),
          
      setDeleteSignups(initDeleteSignups);
```

IMO it's easier to read when you're not passing a function into a function

2022-05-04 00:19 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +        ((shiftsByPosting as ShiftWithSignupAndVolunteerResponseDTO[]) ?? [])
Will do, not super familiar with apollo 😓

2022-05-04 00:20 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +      );
fair, will make the change : )

2022-05-04 00:22 UTC, MatoPlus commented on frontend/src/components/volunteer/shifts/VolunteerAvailabilityTableRow.tsx
> +          onBlur={(event) => {
hmm, I feel like we should have add a commit hook for it, feeling spoiled : P

2022-05-04 00:53 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingAvailabilities.tsx
> +                      numVolunteers: 0, // TODO: Confirm this is correct for init
I'll use the attribute from the posting query since I'm not querying for that field in the shiftsByPosting query.

2022-05-04 06:16 UTC, LenaNguyen submitted a review, later dismissed
:shipit:

2022-05-05 05:05 UTC, LenaNguyen approved these changes

2022-05-05 12:39 UTC, merged