Side panel
uwblueprint/sistering pull request #278
Opened 2022-04-22 02:54 UTC by briantu

## Ticket link

Closes #176 

## Implementation description
* Created `ScheduleSidePanel.tsx` under `/components/admin/schedule`
* If there are no shifts, the side panel displays no shifts panel
* If there are shifts, the side panel displays shift time header (#173) and admin schedule table (#172)
* Created sample data for testing in `testData.ts` that mimics the response data from backend

## Steps to test
1. Go to `http://localhost:3000/admin/schedule/posting/1` where the side panel is mounted
2. Test that everything works as expected

## What should reviewers focus on?
* Code correctness
* Design correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-22 03:12 UTC, briantu commented
Uhhh didn't realize Joseph made a method to restructure the response to match the structure of the temp shifts data I had before. I think I should be able to directly use the response data, and pass them to the sub components like I have currently? Which one should I go with?

2022-04-24 20:32 UTC, LenaNguyen requested changes

2022-04-24 20:32 UTC, LenaNguyen commented on frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
>    const selectAllSignups = () => {
Sherry and I talked through how we want to implement this page. We'll be handling `updateSignupStatus` and `selectAllSignups` a bit differently. I would doing my other comment about moving `selectedShiftId` first.

When making changes in edit mode (i.e. the edit button of the side panel was clicked) we do not want to directly change the `shifts` state value. 
Here are the steps to modify how we want to handle editing:
1.  add a new state value called `currentlyEditingSignups` of type Signup[]. 
2. In `frontend\src\components\pages\admin\schedule\AdminSchedulePostingPage.tsx` add a new method called `handleSidePanelEditClick(signups)`. It receives the array of singups for the selected shifts. It sets the state value `currentlyEditingSignups` to be this array. 
3. Modify `selectAllSignups` and `updateSignupStatus` to edit the state value `currentlyEditingSignups` instead of `shifts`. 
4. In `frontend\src\components\admin\schedule\ScheduleSidePanel.tsx` and `frontend\src\components\admin\schedule\AdminScheduleVolunteerTable.tsx`, modify the component to accept a prop called `currentlyEditingSignups` and a prop called `onEditSignupsClick`. Pass the state value `currentlyEditingSignups` and the method `handleSidePanelEditClick` from the page component down to the `AdminScheduleVolunteerTable.tsx`.

5. In AdminScheduleVolunteerTable, when `isEditing` is `true`, display `currentlyEditingSignups` instead of `signups` . Also, modify the onClick of the Edit/Save button to do two things: (1) call setIsEditing.toggle like before and (2) call `onEditSignupsClick`

2022-04-24 20:32 UTC, LenaNguyen commented on frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
> +  );
I don't think the page needs to know about the selected shift. It just knows the selected day and passes the shifts for that day into the side panel.

Let's move this state value into the side panel component.

2022-04-24 20:32 UTC, LenaNguyen commented on frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
> +          />
Also naming convention for methods being passed around to handle events is the following:

Component prop method name would be `on<EventName>`. So here it could be `onSelectAllSignupsClick` and `onSignupCheckboxClick`. Then the parent component has a handler method with the convention `handle<EventName>` like `handleSelectAllSignupsClick` and `SignupCheckboxClick`. Sometimes the event name is slightly different between the prop and the handler if there are a lot of handlers. 

Would be nice to handle these name changes last!

2022-04-24 20:32 UTC, LenaNguyen commented on frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
> +//     .flat();
we don't really need this anymore so it can be removed!

2022-04-24 20:32 UTC, LenaNguyen commented on frontend/src/components/volunteer/VolunteerNavbar.tsx
> +    <Box px="90px" boxShadow="md" position="relative">
I added the box shadow in another PR.  What does position relative do?

2022-04-24 20:32 UTC, LenaNguyen commented
> 

we should directly use the shift response data like you currently have!

2022-04-24 20:33 UTC, LenaNguyen commented
> Uhhh didn't realize Joseph made a method to restructure the response to match the structure of the temp shifts data I had before. I think I should be able to directly use the shifts response data, and it to the side panel like I have currently? Which one should I go with?

We should directly use the shift response data!

2022-04-28 14:53 UTC, LenaNguyen commented on frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
> +            ))}
Instead of having essentially the same code copied over, you can....

2022-04-28 22:53 UTC, LenaNguyen requested changes
Great job incorporating the changes! 
 Run `yarn fix` to address lint warnings.
 
 We still need to handle save but this can be done in a different ticket.

2022-04-28 22:53 UTC, LenaNguyen commented on frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
> +  // });
Instead of using the test data, can you uncomment this query and create a new state variable called `shifts` of type  `ShiftWithSignupAndVolunteerGraphQLResponseDTO[]` and then pass this into the side panel component instead?

It should work the same and then test data can be removed! The seed data for posting id 1 has shifts but no signups yet. you can add them by logging in as a volunteer with `sistering+volunteer@uwblueprint.org` and the normal password.

Then do this graphql mutation can create signups. Feel free to add
```
mutation CreateShiftSignups{
  createShiftSignups(
    shifts: [ { shiftId: "1", userId: "2", numVolunteers: 3, note: "test" }, { shiftId: "2", userId: "2", numVolunteers: 3, note: "test" }, { shiftId: "2", userId: "2", numVolunteers: 3, note: "test" }]
  ) {
    shiftId
    userId
    numVolunteers
    note
  }
}
```

2022-04-29 02:28 UTC, briantu commented on frontend/src/components/pages/admin/schedule/AdminSchedulePostingPage.tsx
> +    }
Yeah, `const signupsCopy = [...currentlyEditingSignups];` was doing a shallow copy - I think that's what caused it. Using `lodash.cloneDeep` now for deep copy.

2022-04-29 04:17 UTC, briantu commented
Btw, I realized it is possible to change selected shifts from the dropdown while still in edit mode. How do we want to prevent this from happening? Also, just to double check - we will be making the days on the calendar selectable right? Because I think I need the selected date prop for the side panel to show when there are no shifts for that day.

2022-04-30 00:36 UTC, LenaNguyen commented
> Btw, I realized it is possible to change selected shifts from the dropdown while still in edit mode. How do we want to prevent this from happening? Also, just to double check - we will be making the days on the calendar selectable right? Because I think I need the selected date prop for the side panel to show when there are no shifts for that day.

Yeah to do that we will need to lift the state. As for displaying the selected date, the side panel will assume that all shifts passed in are for the same day. So you can just show the date of the first shift.

These fixes will be done in a different pr.

2022-04-30 01:05 UTC, LenaNguyen approved these changes
![](https://media.giphy.com/media/JlpjgShzDsrMIyFu5U/giphy.gif)

2022-04-30 01:43 UTC, merged