Include Employee Info in POC Card
uwblueprint/sistering pull request #296
Opened 2022-04-29 04:40 UTC by Boyazhang1

## Ticket link

Closes #248 

## Implementation description
* Update the getPosting method in the postingService to return employee's name, email, phone number
* Fetch the employee information and display in the POC card for in the PostingDetails component

## Steps to test
1. Navigate to http://localhost:3000/volunteer/posting/1 as an admin, verify the points of contact displays the Edna test employee card

<img width="382" alt="Screen Shot 2022-04-28 at 9 39 48 PM" src="https://user-images.githubusercontent.com/82241706/165885991-f1760316-549a-4ce9-8179-730fa551bf4a.png">

## What should reviewers focus on?
* the postingService functions work as intended with the new changes
* the PostingDetails component fetches the correct data and displays it correctly

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-04-30 01:09 UTC, sherryhli requested changes
Last couple of minor things!

2022-04-30 01:09 UTC, sherryhli commented on backend/services/implementations/postingService.ts
> +  userService: IUserService,
This function can be made a method within the class so that it `this.userService` could be accessed

2022-04-30 01:09 UTC, sherryhli commented on backend/services/implementations/postingService.ts
> +    const employeesArr: EmployeeUserResponseDTO[] = await convertToEmployeeUserResponseDTO(
Nit
```suggestion
    const employeeUsers: EmployeeUserResponseDTO[] = await convertToEmployeeUserResponseDTO(
```

2022-04-30 01:09 UTC, sherryhli commented on backend/types.ts
> +  employees: EmployeeUserResponseDTO[];
Could you please remove all usages of `EmployeeResponseDTO` in the codebase?

2022-04-30 19:27 UTC, Boyazhang1 commented on backend/types.ts
> +  employees: EmployeeUserResponseDTO[];
yup will do

2022-04-30 21:14 UTC, sherryhli submitted a review, later dismissed
Looks good! Please remove the commented out code if you can

2022-05-01 01:35 UTC, sherryhli approved these changes

2022-05-01 01:37 UTC, merged