Add hotjar/GA integration for analytics
uwblueprint/sistering pull request #303
Opened 2022-05-05 02:49 UTC by MatoPlus

## Ticket link

Closes #298

## Implementation description
* Followed ingration steps in #298 and [this guide](https://medium.com/@romansorin/using-hotjar-and-google-analytics-with-next-js-to-track-behavior-a2283d659767) and [this guide](https://blog.saeloun.com/2022/02/17/how-to-integrate-react-app-with-google-analytics.html)

## Steps to test
1. Merge code into main and deploy to sistering-dev
2. Visit at least 2 different pages
3. Go to Hotjar/GA respectively, ensure that respective events shows up in analytics after a while

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [X] I have run the appropriate linter(s)
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-05-06 13:34 UTC, LenaNguyen requested changes

2022-05-06 15:04 UTC, JoshuaYe submitted a review, later dismissed
Looks good to me, thanks!

2022-05-07 17:59 UTC, MatoPlus commented on frontend/src/App.tsx
> +const HJSV = 6;
vault currently down will do this when I get the chance : )

2022-05-07 18:19 UTC, LenaNguyen approved these changes

2022-05-16 04:08 UTC, merged