Update status when removing volunteer + use API data for table
uwblueprint/sistering pull request #304
Opened 2022-05-06 01:27 UTC by lambo-liu

## Ticket link

Closes #250 

## Implementation description
* Implemented the API call for the remove volunteer modal
* Connected table data with results from GraphQL API call
* Fixed minor bugs in the volunteer table, such as duplicate component keys.

## Steps to test
1. Navigate to `http://localhost:3000/admin/schedule/posting/{id}` and check that the table is being filled with the correct data.
2. Try removing a volunteer and see if the status changes to CANCELED in the backend

## What should reviewers focus on?
* Correct implementation & functionality

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-05-07 21:12 UTC, LenaNguyen requested changes
I'm using the seed data rn and there seems to be a bug where the remove modal does not pop up for all rows??? It looks like it might be every other row

2022-05-07 21:12 UTC, LenaNguyen commented on frontend/src/components/admin/schedule/AdminScheduleTableRow.tsx
> +            status="CANCELED"
PENDING

2022-05-07 21:18 UTC, LenaNguyen reviewed
Also, in a different pr, we'll need to update the logic of the table rows a bit. We want to render a row for every day of the week. If there are no shifts for that day then we display "No Shifts Available". If there are no volunteers for the shifts, then we display the shift time followed by "No volunteers".

Designs:
![image](https://user-images.githubusercontent.com/43686735/167271971-949bd897-572d-4080-89b1-6449f1b1ca0e.png)


Current: 
![image](https://user-images.githubusercontent.com/43686735/167271982-42ad189e-ad5a-40ea-8379-254ad23fc13e.png)

2022-05-10 05:40 UTC, LenaNguyen reviewed
I addressed the pr comments but will need someone else to review/approve now!

2022-05-10 13:04 UTC, MatoPlus submitted a review, later dismissed
[last commit](https://github.com/uwblueprint/sistering/pull/304/commits/f487021491c32a6425c02f8df16ce7ca526d0d96) LGTM

2022-05-11 01:20 UTC, LenaNguyen approved these changes

2022-05-11 01:26 UTC, LenaNguyen approved these changes

2022-05-11 02:25 UTC, LenaNguyen approved these changes

2022-05-11 02:31 UTC, merged