initial implementation, updated styles to use text styles in /theme
uwblueprint/sistering pull request #373
Opened 2022-05-29 00:17 UTC by eevanwong

## Ticket link

Closes #216 

## Implementation description
* Implemented page for resetting password (pg where you enter your email) 

## Steps to test
1. go to localhost:3000/reset-password

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-05-29 00:19 UTC, eevanwong commented
![image](https://user-images.githubusercontent.com/71536798/170846793-3da90095-7435-4ed6-be24-0405643ef15d.png)

2022-05-29 00:20 UTC, eevanwong commented
Need to also note that this PR includes small changes to my previous PR, as I did not use proper text styles, can test by going to http://localhost:3000/create-account.

pic:
![image](https://user-images.githubusercontent.com/71536798/170846819-03e6cb9a-9ad5-4a9d-ba4d-74a4d326eae8.png)

2022-05-29 23:14 UTC, MatoPlus requested changes
Looking good! just some stylistic requests : )

2022-05-29 23:14 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +            <Logo />
Can we use `<Image src={Sistering_Logo} alt="Sistering logo" h={32} />` instead? Similarly, can you change our existing ReactComponent logos into Image components?

2022-05-29 23:14 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +        <Box backgroundColor="#f4f4f4" flexGrow={6} />
let's use our color scheme in `color.ts`:
```suggestion
        <Box backgroundColor="background.light" flexGrow={6} />
```

2022-05-29 23:14 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +            <Box marginLeft="43px" marginRight="43px" marginBottom="36px">
```suggestion
            <Box mx="43px" mb="36px">
```
use shorthand, especially for longer prop names

2022-05-29 23:14 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +        <Box backgroundColor="#fff" flexGrow={4}>
```suggestion
        <Box backgroundColor="background.white" flexGrow={4}>
```
use color.ts

2022-05-29 23:14 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +          <Box maxWidth="480px" margin="8vh auto 0 auto">
please try to avoid aggregating props into one for readability
```suggestion
          <Box maxWidth="480px" mt="8vh" mx="auto">
```

2022-05-29 23:14 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +              <Text textStyle="display-large" paddingBottom="24px">
```suggestion
              <Text textStyle="display-large" pb="24px">
```
short hand example :P

2022-05-30 22:32 UTC, AdrianaCeric commented on frontend/src/components/pages/CreateAccountPage.tsx
> +import logo from "../../assets/Sistering_Logo.svg";
Just to make things consistent with other files, I would call this Sistering_Logo instead of logo, but this is honestly nitpick lol

2022-05-30 22:32 UTC, AdrianaCeric approved these changes

2022-05-30 23:47 UTC, eevanwong commented on frontend/src/components/pages/CreateAccountPage.tsx
> +import logo from "../../assets/Sistering_Logo.svg";
Nah dw bout that, consistency is important :). Made the change.

2022-05-31 00:33 UTC, MatoPlus approved these changes
lgtm with nit

2022-05-31 00:33 UTC, MatoPlus commented on frontend/src/components/auth/ResetPassword.tsx
> +import logo from "../../assets/Sistering_Logo.svg";
nit: here as well `Sistering_Logo` 😄

2022-05-31 00:34 UTC, merged