Auth Navbar when users not logged in
uwblueprint/sistering pull request #379
Opened 2022-05-30 23:44 UTC by eevanwong

## Ticket link

Closes #219 

## Implementation description
* Added navbar when user is not logged in (for all pages that can be displayed when user is not logged in)
![image](https://user-images.githubusercontent.com/71536798/171068670-ed348052-ff80-4334-980f-7e353d7e676f.png)

## Steps to test
1. Go to any page that is allowed when not logged in (e.g localhost:3000/login)

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-01 03:25 UTC, MatoPlus requested changes
Looks great! Just couple of follow-ups from me and it's ready to merge : )

2022-06-01 03:25 UTC, MatoPlus commented on frontend/src/App.tsx
> +                  {authenticatedUser ? "" : <AuthNavbar />}
```suggestion
                  {authenticatedUser ? undefined : <AuthNavbar />}
```
would this make more sense semantically?

2022-06-01 03:25 UTC, MatoPlus commented on frontend/src/components/auth/AuthNavbar.tsx
> +            mr="20px"
A follow-up item is to make this the default style for the `MenuButton` component by editing `theme/index.ts` to reduce redundancy a bit. This is optional

2022-06-01 03:25 UTC, MatoPlus commented on frontend/src/components/auth/AuthNavbar.tsx
> +        </Button>
Unless @JoshuaYe said otherwise, I think opening the link in the current page would flow better (rather than open new tab)

Let's try to avoid `window.open` and use Chakra UI's built in link component

```suggestion
        <Link href="https://sistering.org/">
          <Button leftIcon={<ArrowBackIcon w={8} h={8} />} variant="link">
            Back to Main
          </Button>
        </Link>
```

2022-06-01 03:33 UTC, MatoPlus commented on frontend/src/App.tsx
> +                  {authenticatedUser ? "" : <AuthNavbar />}
This is smart but doesn't quite work out: https://github.com/uwblueprint/sistering/pull/381
we have another navbar for unauth users in the account creation flow.

2022-06-02 02:35 UTC, eevanwong commented on frontend/src/components/auth/AuthNavbar.tsx
> +            mr="20px"
I'm a bit uncertain if what I pushed is what you wanted. I initially tried doing adding it for the MenuButton component like so:
![image](https://user-images.githubusercontent.com/71536798/171538433-68e36c90-a234-40d3-bf19-b8230728fb43.png)

![image](https://user-images.githubusercontent.com/71536798/171538475-c4551589-eb81-4afe-949f-7fc2e1f6a868.png)

But the styles did not change. It only changed when I implemented the MenuButton as this, and set a `menuButton` variant for the button.

2022-06-02 03:09 UTC, MatoPlus commented on frontend/src/App.tsx
> +                  {authenticatedUser ? "" : <AuthNavbar />}
hmm sure, I think we can assume that for now but honestly, I don' think there are too many public pages anyways as we currently just manually insert the appropriate navbar into each page. For now, we can go with the suggestion you provided for now.

2022-06-02 03:11 UTC, MatoPlus commented on frontend/src/components/auth/AuthNavbar.tsx
> +            mr="20px"
I think your workaround is good! Chakra UI theme can be a bit ambiguous at times.

2022-06-03 15:41 UTC, eevanwong commented on frontend/src/App.tsx
> +                  {authenticatedUser ? "" : <AuthNavbar />}
On second thought that doesnt work as putting it in App.tsx would not function unless the component that is using the useLocation is in the encapsulated by the Router component. 

Ig this can be an improvement for future stuff. We can put all navbars in a single component and make it dynamic based on routes. I'll go with just manually insertting it into the public components.

2022-06-04 16:58 UTC, MatoPlus approved these changes
LGTM

2022-06-04 19:43 UTC, merged