Create Employee/Volunteer User when "Create Account" is clicked (With GraphQL)
uwblueprint/sistering pull request #417
Opened 2022-06-14 01:12 UTC by AdrianaCeric

## Ticket link

Closes #354 

## Implementation description
* Add queries to create employee and volunteer users (Rickson & Adriana)
* Added error handling and loading stuff (Rickson)

## Steps to test
1. Go to Account Creation form and create a user

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-15 00:22 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +    }
```suggestion
      await createEmployee({
        variables: {
          employee,
        },
      });
```
actually, I don't think we need to catch errors since we handle them in the error modal

2022-06-15 00:22 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +    }
idem
```suggestion
      await createVolunteer({
        variables: {
          volunteer,
        },
      });
```

2022-06-15 00:38 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +                        email: "email123@gmail.com",
no action: we will need to hook up the account creation page to accept an email somehow...

2022-06-15 00:39 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +                        title: "",
@JoshuaYe when we initially create an employee, the title is unset, can you confirm that this is ok?

2022-06-15 00:40 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +                        branchId: 0,
@JoshuaYe when we initially register an employee, how do we set their branch? Can it be an arbitrary set initially?

2022-06-15 00:41 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +  const onEmployeeCreate = async (employee: any) => {
Ideally we should create a type for this employee

2022-06-15 00:42 UTC, MatoPlus requested changes
Just some nits and suggesions

2022-06-18 23:05 UTC, eevanwong commented on frontend/src/components/pages/NewAccountPage.tsx
> +  const onEmployeeCreate = async (employee: any) => {
+1

2022-06-18 23:12 UTC, eevanwong commented on frontend/src/components/user/AccountForm.tsx
> +  onVolunteerCreate: (volunteer: any) => void;
It's best practice to avoid `any` typing. Exploring the other types in `UserType.ts`.

```
export type UserDTO = {
  id: string;
  firstName: string;
  lastName: string;
  role: Role;
  phoneNumber: string | null;
};

export type VolunteerDTO = {
  id: string;
  hireDate: Date;
  dateOfBirth: Date | null;
  pronouns: string | null;
  skills: SkillResponseDTO[];
  branches: BranchResponseDTO[];
};
```

This might be something to look into. If this doesn't work, then you might need to create your own type.

2022-06-20 22:36 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +                        title: "",
Not used in design currently. Potentially, leave this out in schema.

2022-06-20 22:43 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +                        branchId: 0,
TODO: create ticket

2022-06-27 22:28 UTC, AdrianaCeric commented on frontend/src/components/user/AccountForm.tsx
> +                        branchId: 0,
Is this convo resolved?

2022-06-27 22:29 UTC, AdrianaCeric commented on frontend/src/components/user/AccountForm.tsx
> +                        title: "",
@JoshuaYe ^

2022-06-27 22:32 UTC, AdrianaCeric commented on frontend/src/components/user/AccountForm.tsx
> +                        email: "email123@gmail.com",
Is there a ticket for this or do we create one?

2022-06-27 22:53 UTC, MatoPlus requested changes
still missing 2 lines of types

2022-06-28 00:09 UTC, MatoPlus approved these changes
LGTM

2022-06-28 00:50 UTC, merged

2022-06-28 00:51 UTC, AdrianaCeric commented
this is still sus so