Admin homepage posting card
uwblueprint/sistering pull request #446
Opened 2022-06-25 23:39 UTC by lambo-liu

## Ticket link

Closes #343 
Closes #344 

## Implementation description
* Implemented the Admin / Super Admin posting cards
* Rendering depends on the Posting's states, see [Figma](https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Sistering-%2F-Admin-Experience?node-id=1420%3A39607)
* Backend posting status doesn't correspond with frontend, so they are resolved as discussed w/ Rickson. See getPostingStatus() method for details.
* Preview:
<img width="1439" alt="Screen Shot 2022-06-25 at 7 29 18 PM" src="https://user-images.githubusercontent.com/47638847/175793624-5b40397a-f301-4192-8be9-b75aa7efc364.png">

## Steps to test
1. Navigate to http://localhost:3000/ with an admin account (this should also work for employees, but backend currently unauthorizes employees to retrieve postings).
2. Check that the cards render according to designs. Can try adding more postings with different statuses.

## What should reviewers focus on?
* Correctness of rendering / matches designs

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-25 23:40 UTC, lambo-liu commented
For terminology in this ticket, we assume that (admin --> super admin) and (employee --> admin).

2022-06-27 13:04 UTC, MatoPlus reviewed
Looks good at the surface. Will dig deeper into review today. Do let me know when this gets merged so I can do the migration on staging.

2022-06-27 23:35 UTC, MatoPlus commented on frontend/src/components/pages/Default.tsx
> +      </SimpleGrid>
@briantu relevant for your homepage query/integration ticket

2022-06-27 23:41 UTC, MatoPlus commented on frontend/src/components/admin/AdminPostingCard.tsx
> +              } /* TODO: Link to review registrants page */
Is this basically to the `admin/schedule/posting/{id}` route?

2022-06-27 23:44 UTC, MatoPlus commented on frontend/src/components/admin/AdminPostingCard.tsx
> +                <MenuItem>Delete</MenuItem>
Can you actually attach the `DeleteModal` to open on the click handler? It should just be adding a state and passing in the args you want for the text you want to show in the modal

2022-06-28 00:32 UTC, MatoPlus requested changes
small request and LGTM!

2022-07-09 23:09 UTC, MatoPlus commented on frontend/src/components/volunteer/PostingCard.tsx
> +            See Posting Details
can you revert this?

2022-07-09 23:10 UTC, MatoPlus commented on frontend/src/components/volunteer/PostingCard.tsx
> +            )}`}
can you revert this as well?

2022-07-09 23:10 UTC, MatoPlus requested changes
LGTM aside from the comments. I think you're the implementation we want : (

2022-07-09 23:36 UTC, MatoPlus approved these changes
Ship it ⚓🛳️

2022-07-09 23:38 UTC, merged