Neel/user profile mid side panel
uwblueprint/sistering pull request #449
Opened 2022-06-26 21:33 UTC by neelismail01

## Ticket link
https://app.zenhub.com/workspaces/sistering-614f8dad6afeb8001d428787/issues/uwblueprint/sistering/402
Closes #402 

## Implementation description
* Utilized the Chakra UI Drawer and Menu components and customized them as per the designs

## Steps to test
1. Visit `http://localhost:3000/admin/users` and verify the UI looks like the designs on Figma

## What should reviewers focus on?
* Does the handling of selected branches seem appropriate?

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-06-27 12:45 UTC, MatoPlus reviewed
Please run a 'yarn fix` to fix the linting issues

2022-06-27 12:53 UTC, MatoPlus commented
@neelismail01 I think you did #405 instead of #402. Difference is kinda subtle, I think you can close both tickets after a few more changes, make 2 drawers, one for the profile drawer and one for the multi-branch drawer

2022-06-27 12:56 UTC, MatoPlus requested changes

2022-06-27 12:56 UTC, MatoPlus commented on frontend/src/components/pages/admin/user/ProfileDrawer.tsx
> +    <>
I don't think we need this outer wrapper
```suggestion
```

2022-06-27 12:56 UTC, MatoPlus commented on frontend/src/components/pages/admin/user/ProfileDrawer.tsx
> +          <DrawerHeader>7 User(s) Selected</DrawerHeader>
This is for #405

2022-06-27 12:56 UTC, MatoPlus commented on frontend/src/components/pages/admin/user/ProfileDrawer.tsx
> +            </Box>
Let's put this into a separate component since it'll be used in two drawers. say `BranchMultiSelector.tsx` or something similar.

2022-07-05 00:10 UTC, neelismail01 commented on frontend/src/components/pages/admin/user/ProfileDrawer.tsx
> +            </Box>
Done.

2022-07-05 00:10 UTC, neelismail01 commented on frontend/src/components/pages/admin/user/ProfileDrawer.tsx
> +          <DrawerHeader>7 User(s) Selected</DrawerHeader>
I made a separate component for the multi-user drawer which should address #405

2022-07-05 00:10 UTC, neelismail01 commented on frontend/src/components/pages/admin/user/ProfileDrawer.tsx
> +    <>
Done.

2022-07-06 04:54 UTC, MatoPlus reviewed
Nothing pops out immediately but I'll get my review in soon tmw

2022-07-07 01:15 UTC, MatoPlus approved these changes
Clean. Ship it 🔥

2022-07-07 04:11 UTC, merged