Skills crud resolvers
uwblueprint/sistering pull request #47
Opened 2021-11-02 23:13 UTC by briantu

## Ticket link

Closes #44

## Implementation description
* Defined `SkillDTO` types
* Created `SkillService` with CRUD methods and GraphQL resolvers
* Added a unique constraint on skill name

## Steps to test
1. Start docker and `run docker-compose up --build`
2. Run `docker exec -it sistering-backend-1 /bin/bash -c "npx prisma generate"` to update the prisma client library
3. Go to http://localhost:5000/graphql
4. Verify all the GraphQL queries and mutations related to the Prerequisite Model are working as expected

## What should reviewers focus on?
* Functional GraphQL queries & mutations

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-11-13 20:54 UTC, tamim-khan reviewed
Overall lgtm!

2021-11-13 20:54 UTC, tamim-khan commented on backend/graphql/resolvers/skillResolvers.ts
> +      const newSkill = await skillService.createSkill(skill);
Is there validation somewhere for `skill.name` being null or empty string?

2021-11-13 20:54 UTC, tamim-khan commented on backend/services/implementations/skillService.ts
> +  }
nit: How big is the skills table expected to be? Might want to consider pagination for large tables to avoid long responses. Probably okay to leave it as is for now if it's not expected to be very large.

2021-11-13 20:54 UTC, tamim-khan commented on backend/graphql/resolvers/skillResolvers.ts
> +    },
Same here, might want to add validation for `skill.name` if it's already checked.

2021-11-17 02:17 UTC, lambo-liu commented on backend/services/implementations/skillService.ts
> +  }
Asked about this and I think it's ok

2021-11-17 02:17 UTC, lambo-liu commented on backend/services/implementations/skillService.ts
> +          name: skill.name,
Designers confirmed that it's okay for the `name` to be case-insensitive. Good catch though!

2021-11-24 01:17 UTC, sherryhli requested changes
Sorry for the late review. Almost good to go, just a few minor changes :)

2021-11-24 01:17 UTC, sherryhli commented on backend/services/implementations/skillService.ts
> +      }
Prisma's `update` method throws a `RecordNotFound` exception if not found, this check is not needed, it will be handled by the try-catch

Ref: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type-4

2021-11-24 01:17 UTC, sherryhli commented on backend/services/implementations/skillService.ts
> +      }
This check is not needed (also do not need to query for `skillToDelete`), the Prisma `delete` method will throw an exception if not found

Ref: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type-6

2021-11-24 01:17 UTC, sherryhli commented on backend/graphql/resolvers/skillResolvers.ts
> +      return skillService.deleteSkill(id);
GraphQL best practice is to always return a value from operations so for deletions, it might make sense to return the ID of the deleted item.

Up to you if you want to make the change here, we can also create a separate task to fix this and the other delete operations.

2021-11-24 01:50 UTC, briantu commented on backend/services/implementations/skillService.ts
> +      });
Haha, I don't know how that get there 😅. Deleted!

2021-11-24 01:51 UTC, briantu commented on backend/services/implementations/skillService.ts
> +      }
Got it, thanks! Removed.

2021-11-24 01:52 UTC, briantu commented on backend/services/implementations/skillService.ts
> +      }
Fixed!

2021-11-24 01:53 UTC, briantu commented on backend/graphql/resolvers/skillResolvers.ts
> +      return skillService.deleteSkill(id);
We'll do it here. Now it returns the deleted ID!

2021-11-24 02:12 UTC, sherryhli approved these changes
Nice, 🚢 it!

2021-11-24 03:05 UTC, merged