438-Send an Email along with creating the userInvite row
uwblueprint/sistering pull request #491
Opened 2022-07-14 21:21 UTC by eevanwong

## Ticket link

Closes #438 

## Implementation description
* The createUserInvite resolver also sends an email once the userInvite is inserted into the database.

## Steps to test
1. Use this query:
```
mutation testCreateUserInvite($email: String!) {
   createUserInvite(email: $email, role: VOLUNTEER) {
     uuid
   }
}
```
And in your query variables, use whichever email you want (spam or smthn) and run the mutation, it should send this email:
![image](https://user-images.githubusercontent.com/71536798/179088142-8ba6c3f5-64ca-4b37-95fa-3c80986df1b4.png)

The link will take you to the page to create your account:
![image](https://user-images.githubusercontent.com/71536798/179088272-f4de6f8e-efd7-4606-8f0b-028dbafe22a4.png)

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-14 22:12 UTC, MatoPlus commented on backend/graphql/index.ts
> +    dateTimeString
huh, is our column length limit this small?

2022-07-14 22:12 UTC, MatoPlus commented on backend/graphql/index.ts
> +    createUserInvite: authorizedByAllRoles(),
Hmm can you explain this change? Does doesn't look right. Only admins should be able to invite other admins + employees

2022-07-14 22:40 UTC, MatoPlus commented on backend/graphql/index.ts
> +    dateTimeString
I don't think my local eslint likes this change but no action needed

2022-07-14 22:47 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +        )}`,
idem, this can be reverted

2022-07-14 22:47 UTC, MatoPlus commented on backend/services/interfaces/userService.ts
> +  ): Promise<UserInviteResponse>;
idem

2022-07-14 22:47 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +      return userService.createUserInvite(email, role, emailService);
idem

2022-07-14 22:48 UTC, MatoPlus requested changes
Looks great overall! Let's clean the code a bit and ship it 🧹

2022-07-15 00:33 UTC, eevanwong commented on backend/graphql/index.ts
> +    createUserInvite: authorizedByAllRoles(),
Thats my bad, I think I made that change to test something when I was dealing with a bug but forgot to revert it.

2022-07-15 02:18 UTC, MatoPlus commented on backend/graphql/index.ts
> +    dateTimeString
oh here's the same linting issue that appeared on my local machine

2022-07-15 02:19 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +        )}`,
```suggestion
        `Failed to create user invite row. Reason = ${getErrorMessage(error)}`,
```
Let's revert

2022-07-15 02:20 UTC, MatoPlus reviewed
There's still some unused imports. Besides the linting problems, code looks good to merge!

2022-07-16 15:07 UTC, MatoPlus approved these changes
Ship it!

2022-07-16 17:41 UTC, MatoPlus requested changes

2022-07-16 17:41 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +`;
@eevanwong can you use the new template I provided? Please rebase and use that instead.

2022-07-16 17:46 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +`;
https://github.com/uwblueprint/sistering/pull/490/files#diff-44e16111f2add2306d8f7075373015dde35857eb70c1e351491e7e7452f60942R35

2022-07-16 17:58 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +      const SUBJECT = "Invitation to Sistering Platform";
let's update this to match design I think it should be "Welcome to your ${role} account"

2022-07-16 18:00 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +      const SUBJECT = "Invitation to Sistering Platform";
https://www.figma.com/file/TWJTNWjK75A6VgSisySTLe/Sistering-%2F-Admin-Experience?node-id=1643%3A48828

2022-07-16 18:01 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +        results.role,
this should be title case, eg: `Volunteer` or `Administrator`

2022-07-16 18:19 UTC, MatoPlus approved these changes

2022-07-16 18:20 UTC, merged