Pending invitations modal
uwblueprint/sistering pull request #511
Opened 2022-07-17 00:45 UTC by briantu

## Ticket link

Closes #479

## Implementation description
* Created `UserInvitesModal.tsx` and `UserInvitesTable.tsx` in `frontend/src/components/admin`
* Hooked up modal to "Invitations" button in `AdminUserManagementPageHeader.tsx`
* Created `UserInviteTypes.ts` and added `UserInviteDTO`
* Made some changes to the Table brand theme

## Steps to test
1. Go to `http://localhost:3000/admin/users`
2. Click on "Invitations" button to open the modal
3. Check modal looks good

## What should reviewers focus on?
* Code correctness
* Design correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-17 00:49 UTC, MatoPlus commented on frontend/src/components/admin/UserInvitesModal.tsx
> +                {
Can you add a TODO comment to populate this?

2022-07-17 01:02 UTC, MatoPlus requested changes
Can you change the tabs such that it filters by role?

2022-07-17 01:28 UTC, MatoPlus commented on frontend/src/components/admin/UserInvitesTable.tsx
> +      </Table>
I think this should be insider the Tab component within a TabPanels?

2022-07-17 01:28 UTC, MatoPlus reviewed
Aside from request, this looks good to merge

2022-07-18 22:55 UTC, briantu commented on frontend/src/components/admin/UserInvitesTable.tsx
> +      </Table>
Done! I decided to use a state for the selected tab cuz I think it's easier than having two TabPanels with a Table in each.

2022-07-18 23:19 UTC, MatoPlus commented on frontend/src/components/admin/UserInvitesTable.tsx
> +                  />
FollowUP: we need to call delete user invite by email

2022-07-18 23:22 UTC, MatoPlus approved these changes
LGTM

2022-07-18 23:25 UTC, merged