User Account Creation Flow
uwblueprint/sistering pull request #517
Opened 2022-07-20 02:01 UTC by eevanwong

## Ticket link

Closes #489 

## Implementation description
* Integrated user invites in `/admin/users`, can now send user invites to emails
* users can click on link in email and go through entire account creation flow (create account page start, newaccountform)
* before user is created after form submission, we check if a userinvite exists (if so, create account, then proceed to account creation successful page), then the userinvite is deleted.

## Steps to test
1. Go to `/admin/users` and click on `Add Volunteer` and enter an email
2. Go through account creation process from email (it might be in spam)
3. once completed, try logging in to confirm it works.

Note: If you verify your email (you get another email after you create an account to verify your email with firebase), then you it will prevent you from using that same email to create a new account on sistering to test, so ignore the verification email. 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-20 02:10 UTC, eevanwong commented
@MatoPlus I realize that for #468 we're supposed to check the 2 week limit, but in the schema itself there is no type in there. I believe need to update the schema myself?

2022-07-20 02:39 UTC, MatoPlus commented
> @MatoPlus I realize that for #468 we're supposed to check the 2 week limit, but in the schema itself there is no type in there. I believe need to update the schema myself?

What type are you referring to? For the 2 week limit, I was thinking we can just compare the create date to today and if that is older than 2 weeks, we delete it.

2022-07-20 12:44 UTC, MatoPlus reviewed
Some nits and comments. Will try to test this later tonight.

2022-07-20 12:44 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +          `http://localhost:3000/create-account?token=${results.uuid}`,
Let's add a env var to reference this

2022-07-20 12:44 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +    history.push("/account-created");
Would this make more sense?
```suggestion
    if (!createEmployeeError) {
      await deleteUserInvite({
        variables: {
          email: userInvite?.email,
        },
      });
    
      history.push("/account-created");
    }
```

2022-07-20 12:44 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +          email={userInvite?.email} // TODO: Replace with firebase email
nice! I think you can remove the TODO comment now?

2022-07-20 12:44 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +  };
Can you re-implement this method using moment.js and put it inn `DateTimeUtils`?

2022-07-22 01:40 UTC, MatoPlus requested changes
left some requests

2022-07-22 03:40 UTC, eevanwong commented on frontend/src/components/user/AccountForm.tsx
> +  };
Would this be fine? 
```
hireDate: moment(new Date()).format("YYYY-MM-DD"),
```

2022-07-22 03:47 UTC, AdrianaCeric commented on backend/services/implementations/userService.ts
> +      if (userInvite == null) {
[extreme nitpick] but ??? 
```suggestion
      if (userInvite === null) {
```

2022-07-22 12:17 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +  };
looks good to me!

2022-07-22 12:22 UTC, MatoPlus commented on frontend/src/components/admin/AddVolunteerModal.tsx
> +      console.log("Error with creating volunteer");
can we render the error modal instead on error? See other page for examples

2022-07-22 12:22 UTC, MatoPlus commented on frontend/src/components/admin/AddAdminModal.tsx
> +      console.log("Error with creating volunteer");
can we replace this with an error modal?

2022-07-23 01:48 UTC, eevanwong commented
As a heads up, I added an SITE_URL as a env variable in the repos main .env file. This wil be http://localhost:3000 in a local environment, and https://sistering-dev.web.app for prod.

@MatoPlus Can you remind me how to push my .env to vault?

2022-07-23 21:49 UTC, MatoPlus reviewed
This looks good to me from a high level overview. I'll dig deeper and test it out later in the work session today and hopefully get this merged EOD

2022-07-24 01:50 UTC, MatoPlus commented
A followup is that a super admin should not be able to invite a user that is already a user. I believe this should be changing the `createUserInvite` resolver

2022-07-24 02:03 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +      }
This part is buggy from testing. Should not directly use state after using set action as it is not synchronous.
```suggestion
      if (data.getUserInvite?.role === "EMPLOYEE") {
        setIsAdmin(true);
      }
```

2022-07-24 02:13 UTC, MatoPlus requested changes
Left suggestion

2022-07-24 17:54 UTC, MatoPlus commented on frontend/src/components/pages/NewAccountPage.tsx
> +      }
I think after this gets changed, this PR should be good to change.

2022-07-24 22:44 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +
This doesn't work because email is not a field under the user model, it's managed internally via firebase auth, which means you need to call the firebase service to confirm if there already is an user with that email. If it's too much trouble, we can just remove this.

2022-07-25 12:22 UTC, MatoPlus approved these changes
Thanks! Feel free to merge when you are ready

2022-07-25 19:01 UTC, MatoPlus approved these changes
LGTM!

2022-07-25 21:00 UTC, merged