Integrate User Invites Modal with Backend
uwblueprint/sistering pull request #525
Opened 2022-07-26 00:59 UTC by briantu

## Ticket link

Closes #516

## Implementation description
* Created query resolver for all user invites
* Integrated user invites query and delete user mutation

## Steps to test
1. Go to `http://localhost:3000/admin/users`
2. Open invitations modal
3. Create some sample invitations by clicking on "+" button 
4. Open the invitations modal
5. Check that the invitations just created are shown
6. Check that deleting an invitation works

## What should reviewers focus on?
* Code correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-27 15:32 UTC, MatoPlus commented on backend/graphql/resolvers/userResolvers.ts
> +    },
Thanks for adding this!

2022-07-27 15:36 UTC, MatoPlus requested changes
Made 2 suggestions. Overall looks good. Will leave to @neelismail01 to deep dive and stamp

2022-07-30 23:23 UTC, neelismail01 approved these changes
The code looks good to me. Once you get Rickson's error toast done, feel free to merge.

2022-08-03 23:46 UTC, sherryhli reviewed
Nice to see this new user invite flow! 🔥

2022-08-03 23:46 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +      });
Curious if this adds any noticeable latency to `getUserInvites` queries. I wonder if it might be worth creating a scheduled job for clearing out expired invites, with the added benefit of guaranteed cleanup intervals for the user invite table. Then again, I guess we don't expect there to be loads of expired entries to delete anyways?

2022-08-04 00:41 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +      });
Good point to bring up! We considered this along with sending out reminder emails on a weekly basis via some cronjob. I think @neelismail01 originally dug into it but there was too many unknowns and we ended removing it from final launch scope.

At the moment, we delete any user invites that are expired when we try to query them. ie: before returning query results, if they are expired (past 2 weeks), we delete them instead.

2022-08-04 02:36 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +      });
Got it, makes sense! I think it should work well in practice

2022-08-10 22:46 UTC, MatoPlus approved these changes
Looks good to me. We might wanna follow with some kinda empty state for these tables @a-twh

2022-08-11 19:37 UTC, merged