Migrate DoB and pronouns to user model
uwblueprint/sistering pull request #541
Opened 2022-07-31 16:30 UTC by eevanwong

## Ticket link

Closes #503

## Implementation description
* Changed prisma schema, changed corresponding types in backend and frontend, as well as to graphql schemas.
* 

## Steps to test
1. Use any query with users and they will now have pronouns and date of birth associated with them.

As a general note: I noticed that, while the prisma schema originally made pronouns essential and dateOfBirth nullable, the typing in types didnt reflect that (sometimes both were nullable). How important is it that the type `string` vs `string | null`?

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-07-31 20:44 UTC, MatoPlus commented on backend/graphql/types/userType.ts
> +    pronouns: String!
Like you pointed out in the PR desc, was this originally defaulted to "" or something similar in the service implementation for the resolver?

2022-07-31 20:44 UTC, MatoPlus commented on backend/graphql/types/userType.ts
> +    pronouns: String!
idem

2022-07-31 20:48 UTC, MatoPlus commented on backend/graphql/types/userType.ts
> +    pronouns: String!
https://github.com/uwblueprint/sistering/pull/541/files#diff-9fb1b1d1450d36b06c56517448127a1728819a646db02b29716efa1f89c8df97L751-L752

found it. Hmm I think there was some miscommunication during dev, pronouns should be required according to the account from: https://www.figma.com/file/tOK6AjkaRZ1NBXo191D64C/Sistering-%2F-User-Authentication-Process?node-id=518%3A6949

2022-07-31 20:51 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +                pronouns: volunteerUser.pronouns ?? "",
Could we clear up this and make pronouns required as well?
```suggestion
                pronouns: volunteerUser.pronouns ??,
```

2022-07-31 20:51 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +              pronouns: deletedVolunteerUser.pronouns ?? "",
idem, should not have fallback

2022-07-31 20:56 UTC, MatoPlus requested changes
Made some suggestions, looks like we also need to update https://github.com/uwblueprint/sistering/pull/541/files# since pronouns is now a required field to create users.

2022-07-31 22:26 UTC, eevanwong commented on backend/services/implementations/userService.ts
> +                pronouns: volunteerUser.pronouns ?? "",
The suggested change isnt valid, I need an expression there, do you mean just remove the ?? operator?

2022-07-31 22:28 UTC, eevanwong commented on backend/services/implementations/userService.ts
> +              pronouns: deletedVolunteerUser.pronouns ?? "",
Ok, will remove, I assume thats what you meant in the initial suggestion as well.

2022-08-02 01:56 UTC, MatoPlus commented on backend/services/implementations/userService.ts
> +                pronouns: volunteerUser.pronouns ?? "",
> do you mean just remove the ?? operator?
Yes, that was what I was trying to suggest.

2022-08-02 02:15 UTC, MatoPlus reviewed
can we query the new `pronouns` and `dateOfBirth` field in the `EMPLOYEE_BY_ID` query under the Edit Account page? The updated query should look something like:
```gql
const EMPLOYEE_BY_ID = gql`
  query EmployeeUserById($id: ID!) {
    employeeUserById(id: $id) {
      id
      firstName
      lastName
      email
      dateOfBirth
      pronouns
      phoneNumber
      emergencyContactPhone
      languages
      branches {
        id
        name
      }
    }
  }
`;

```

2022-08-02 02:16 UTC, MatoPlus approved these changes
LGTM with quick suggestion.

2022-08-02 02:17 UTC, MatoPlus commented
Looks like we'll have to reset the staging db for this. Please let me know when merging this.

2022-08-02 02:34 UTC, MatoPlus approved these changes
Thanks for getting this done @eevanwong!

2022-08-02 03:22 UTC, merged