Add schedule flow toasts and closed posting state
uwblueprint/sistering pull request #547
Opened 2022-08-05 03:26 UTC by MatoPlus

## Ticket link

Closes #524

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-07 17:38 UTC, neelismail01 commented on frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
> +              color={isEditing ? "violet" : "purple.600"}
Can we add this colour definition into our theme?

2022-08-08 13:09 UTC, MatoPlus commented on frontend/src/components/admin/schedule/AdminScheduleVolunteerTable.tsx
> +              color={isEditing ? "violet" : "purple.600"}
I don't really see value in that to be honest. Are you talking about "purple.600" that is also the name we refer to in the figma design so I think it's fine.

2022-08-08 21:48 UTC, MatoPlus commented
Looks like I got some lint errors to take care of. I'll try to get them in by EOD

2022-08-08 22:12 UTC, MatoPlus commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +  const toast = useToast();
```suggestion
```

2022-08-08 22:12 UTC, MatoPlus commented on frontend/src/components/pages/admin/posting/PostingFormReviewPage.tsx
> +  const toast = useToast();
```suggestion
```

2022-08-12 01:46 UTC, MatoPlus commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +  // TODO: If posting is closed, we want to disable action to review registrants
```suggestion
```

2022-08-12 21:21 UTC, sherryhli requested changes
Noticed a couple of possible bugs on the "closing date not passed" toast

2022-08-12 21:21 UTC, sherryhli commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +      toast({
Might be nice to add some logic for avoiding duplicate toasts, which can occur if returning to the schedule page after navigating away (e.g. clicking "View Posting" and then "Back")

https://chakra-ui.com/docs/components/toast#preventing-duplicate-toast

![image](https://user-images.githubusercontent.com/30205929/184444818-8a76be11-f36a-413e-adc0-e978df6110d1.png)

2022-08-12 21:21 UTC, sherryhli commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +      toast({
Additionally, I'm seeing something strange with 2 toasts appearing on subsequent visits to the same schedule page 🤔

![schedule-toast](https://user-images.githubusercontent.com/30205929/184446244-5a0c425a-a215-4fcd-b5ae-6a41de80a6e8.gif)

2022-08-12 21:21 UTC, sherryhli commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +          minWidth: "75vw",
Should the toast width match the calendar width?

2022-08-12 22:21 UTC, MatoPlus commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +      toast({
Good catch. I'll investigate

2022-08-12 22:22 UTC, MatoPlus commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +          minWidth: "75vw",
I think it should yea. Let me see if I can make that change.

2022-08-13 20:26 UTC, MatoPlus reviewed
resolved @sherryhli suggestions, still kinda bothered by how the toast in question persist even after we leave the page but I think that's just how toasts are programmed. I'll just put a 10s timer on it.

2022-08-13 21:39 UTC, sherryhli approved these changes
LGTM code-wise

> resolved @sherryhli suggestions, still kinda bothered by how the toast in question persist even after we leave the page but I think that's just how toasts are programmed. I'll just put a 10s timer on it.

Yeah, not sure what the design intent is here, but perhaps a custom-built persistent banner on the schedule page might be more appropriate than a toast. Understandable if there's no capacity to address this though.

2022-08-13 22:46 UTC, MatoPlus commented
> LGTM code-wise
> 
> > resolved @sherryhli suggestions, still kinda bothered by how the toast in question persist even after we leave the page but I think that's just how toasts are programmed. I'll just put a 10s timer on it.
> 
> Yeah, not sure what the design intent is here, but perhaps a custom-built persistent banner on the schedule page might be more appropriate than a toast. Understandable if there's no capacity to address this though.

Yea I think you're right. I'll look other options for components

2022-08-13 22:59 UTC, merged