added toast errors to all mutations
uwblueprint/sistering pull request #548
Opened 2022-08-06 20:59 UTC by eevanwong

## Ticket link

Closes #503 

## Implementation description
* Searched up:
```
`
  mutation 
``` 
to find all mutations that were used. Then I used try catch with toast to pop up a toast error in the event of an error.

## Steps to test
1. The steps are quite tedious, because its essentially going through each page changed to ensure that the toast all work.

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-06 21:22 UTC, MatoPlus commented on frontend/src/components/auth/Logout.tsx
> +      });
This component isn't being used, can revert (optional)

2022-08-06 21:22 UTC, MatoPlus commented on frontend/src/components/auth/RefreshCredentials.tsx
> +      });
This component isn't being used, can revert (optional)

2022-08-06 21:26 UTC, MatoPlus commented on frontend/src/components/crud/CreateForm.tsx
> +    }
This component isn't being used, can revert (optional)

2022-08-06 21:26 UTC, MatoPlus commented on frontend/src/components/crud/UpdateForm.tsx
> +    }
This component isn't being used, can revert (optional)

2022-08-06 21:29 UTC, MatoPlus reviewed
Awesome work. One suggestion is to remove the change the error modal on those pages to be independent of the errors you are handling via toasts. ie: remove them if error modals are only depending on the mutation, otherwise update the render condition such that they won't render when toast is showing.

2022-08-06 21:30 UTC, MatoPlus reviewed
> The steps are quite tedious, because its essentially going through each page changed to ensure that the toast all work.

yea. I say let's test a few on the main pages and let the rest go since the toast render logic is mostly uniform throughout

2022-08-07 18:46 UTC, MatoPlus commented on frontend/src/components/auth/Login.tsx
> -            {loginError && <ErrorModal />}
I guess this was where the double login modal was from. Nice catch.

2022-08-07 18:49 UTC, MatoPlus commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +    }
`submitSignupsError` is still being used as a condition for the error modal. This can be removed.

2022-08-07 18:49 UTC, MatoPlus requested changes
Caught 1 item to chage. Rest LGTM. Will test after the last commit gets in.

2022-08-07 19:00 UTC, eevanwong commented on frontend/src/components/pages/admin/schedule/SchedulePostingPage.tsx
> +    }
Ok, sounds good. Will remove the toast here.

2022-08-07 19:39 UTC, MatoPlus approved these changes
LGTM

2022-08-07 19:40 UTC, merged