Create Shift CRUD Methods and GraphQL Resolvers
uwblueprint/sistering pull request #55
Opened 2021-11-27 20:08 UTC by lambo-liu

## Ticket link

Closes #51 

## Implementation description
* Implemented the following endpoints & CRUD methods for shifts:
* > getShifts
* > getShift
* > createShifts (creates shifts of a posting by bulk)
* > updateShift (updates a single shift)
* > updateShifts (updates shifts of a posting by bulk)
* > deleteShift (deletes a single shift)
* > deleteShifts (deletes all shifts of a posting)

## Steps to test
1. Create a dummy posting using SQL. Here are the following SQL queries to run:
`
insert into branches (id, name) values (1, 'test branch');
insert into postings (id, branch_id, type, title, purpose, responsibilitie, tasks, desired_qualities, mandatory_activities, benefits, working_conditions, num_volunteers) values (1, 1, 'GROUP', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 0);
`
2. Go to `localhost:5000/graphql`, and test the individual queries & resolvers.

Examples:
Create shifts by bulk, using a biweekly recurrence interval
`mutation {
  createShifts(shifts: {
    postingId: "1",
    times: [
      {
        date: "2021-12-16"
        startTime: "01:30"
        endTime: "04:30"
      },
      {
        date: "2021-12-18"
        startTime: "12:00"
        endTime: "16:00"
      }
    ],
    endDate: "2022-01-15",
    recurrenceInterval: BIWEEKLY
  }) {
    id
    postingId
    startTime
    endTime
  }
}`

Update a single shift
`mutation {
  updateShift(id: "1", shift: {
    startTime: "2021-12-16 04:30",
    endTime: "2021-12-16 06:30"
  }) {
    postingId
    startTime
    endTime
  }
}`

## What should reviewers focus on?
* There are lots of validations to be checked. For bulk create / update, make sure that users can only input time blocks within a 1-week timeframe.
* If duplicate DateTimes persist, they should be neglected in the bulk creation process.
* Create/Update procedures should only work with a valid postingId
* Times should be inputted in the `HH:mm` format, and DateTimes should be inputted in the `YYYY-MM-DD HH:mm` format. Any other format should throw an error.
* Check that the functionality checks out and the code is clean!
* Have a good day 🌈 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-11-28 23:16 UTC, sherryhli requested changes
Great progress so far! 😄 This is a big set of changes so I'll be doing another round of review after these comments are addressed

2021-11-28 23:16 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +    }
Not needed due to foreign key constraint :)

2021-11-28 23:16 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +    const newShifts: ShiftResponseDTO[] = await this.createShifts(shifts);
Instead of calling the `deleteShifts` and `createShifts` methods, I think we should call the underlying Prisma methods directly within a transaction to ensure that the update is treated as a single atomic operation, leaving the database with an always consistent state

2021-11-28 23:16 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +      });
This query isn't needed

2021-11-28 23:16 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +      }
Exception will be thrown if shift ID is not found, catch block already handles this

Ref: https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type-6

2021-11-28 23:16 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +      }
See previous comments :)

2021-11-28 23:16 UTC, sherryhli commented on backend/services/interfaces/IShiftService.ts
> +  getDuration(recurrence: RecurrenceInterval): DurationArgs;
Minor stylistic preference but I don't think we should expose helper functions in the interface, which acts as a guarantee of what methods are publicly available from `ShiftService`.

2021-12-04 18:58 UTC, lambo-liu commented on backend/services/implementations/shiftService.ts
> +    }
this should be checked in the `timeBlocks.some` block right above this

2021-12-04 20:11 UTC, lambo-liu commented
@sherryhli updated changes! Feel free to review again. Thanks! 💯

2021-12-06 03:04 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +      await prismaClient.shift.deleteMany({
I took a closer look at the [docs](https://www.prisma.io/docs/guides/performance-and-optimization/prisma-client-transactions-guide) and it looks like we don't need to directly call Prisma methods within the transaction block, calling other functions work too. We can simplify to calling `this.deleteShifts` and `this.createShifts` here.

2021-12-06 03:08 UTC, sherryhli commented on backend/services/interfaces/IShiftService.ts
> +export type DurationArgs = {
Can this be defined locally in the `implementations/shiftService.ts` file?

2021-12-08 00:03 UTC, sherryhli reviewed
One more minor comment!

2021-12-08 00:09 UTC, sherryhli commented on backend/graphql/resolvers/shiftResolvers.ts
> +  },
GraphQL best practice is to always return a value from operations so for deletions, let's return the ID of the deleted item. Unfortunately starter code did not follow this convention 😅

2021-12-18 19:37 UTC, lambo-liu commented on backend/services/implementations/shiftService.ts
> +          moment(tb.startTime, timeFormat) >= moment(tb.endTime, timeFormat),
I don't think so? `startTime` and `endTime` are both in timeFormat and in the same day `date`. So I think when they're parsed they will always be in the same day.

2021-12-18 20:39 UTC, lambo-liu commented
@sherryhli fixed! Let me know if there's anything else 👍

2022-01-04 22:54 UTC, sherryhli reviewed
Sorry for the delay reviewing! A few very minor things left, which I can take of

2022-01-04 22:54 UTC, sherryhli commented on backend/yarn.lock
> +  integrity sha512-kHmoybcPV8Sqy59DwNDY3Jefr64lK/by/da0ViFcuA4DH0vQg5Q6Ze5VimxkfQNSC+Mls/Kx53s7TjP1RhFEDQ==
This is the only yarn.lock dependency change needed, the rest are unused and were deleted in #56

2022-01-04 22:54 UTC, sherryhli commented on backend/Dockerfile
> +RUN apt-get update && apt-get install -y libcurl3
Let's remove the `libssl-dev` dependency above, it should be pulled transitively by the `libcurl3` install

2022-01-04 22:54 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +        true,
```suggestion
        STRICT_MODE,
```

2022-01-04 22:54 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +        true,
```suggestion
        STRICT_MODE,
```

2022-01-04 22:54 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +            true,
```suggestion
            STRICT_MODE,
```

2022-01-04 22:54 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +        }
Can declare and increment both start and end in loop initialization. Side note: is the `startTime.clone()` necessary?

```suggestion
        for (
          let start = startTime.clone(), end = endTime;
          start < endDate;
          start.add(duration.value, duration.unit), end.add(duration.value, duration.unit)
        ) {
          recurringShifts.push({
            startTime: start.toDate(),
            endTime: end.toDate(),
          });
        }
```

2022-01-04 22:54 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +            const newShift = await prismaClient.shift.create({
I think we still need to check that the shift created here is not a duplicate of an existing shift (copy validation logic in `createShift`)

2022-01-07 00:09 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +  async checkConflictingShifts(
@LenaNguyen some context on why we check for conflicts :)

We want to avoid creating duplicate shifts (i.e. 2 shifts associated with the same posting that have the exact same start time and end time. This validation is pretty costly but unless there are significant performance issues, I think it's worthwhile to keep. We wouldn't want the database to be spammed with lots of duplicate entries (either accidentally or maliciously), it'd hurt performance and waste our row count quota in Heroku.

2022-01-09 17:57 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +    const endDate: Moment = moment(shifts.endDate, dateFormat, STRICT_MODE).add(
why do we add a day to the endDate?

2022-01-09 21:01 UTC, LenaNguyen commented on backend/services/implementations/shiftService.ts
> +          let start = startTime.clone(), end = endTime;
why do we copy startTime but not endTime?

2022-01-09 21:03 UTC, LenaNguyen reviewed
> Create a dummy posting using SQL. Here are the following SQL queries to run:
insert into branches (id, name) values (1, 'test branch');
insert into postings (id, branch_id, type, title, purpose, responsibilitie, tasks, desired_qualities, mandatory_activities, benefits, working_conditions, num_volunteers) values (1, 1, 'GROUP', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 0);
Go to localhost:5000/graphql, and test the individual queries & resolvers.

The insert for postings in this PR description is out of date right? I tried running it and the table no longer has some of these colums.

2022-01-09 21:09 UTC, lambo-liu commented
> > Create a dummy posting using SQL. Here are the following SQL queries to run:
> > insert into branches (id, name) values (1, 'test branch');
> > insert into postings (id, branch_id, type, title, purpose, responsibilitie, tasks, desired_qualities, mandatory_activities, benefits, working_conditions, num_volunteers) values (1, 1, 'GROUP', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 0);
> > Go to localhost:5000/graphql, and test the individual queries & resolvers.
> 
> The insert for postings in this PR description is out of date right? I tried running it and the table no longer has some of these colums.

Sorry Lena! Forgot to update these after Brian & Albert changed the schema for postings. Will update this now.

2022-01-09 21:52 UTC, lambo-liu commented on backend/services/implementations/shiftService.ts
> +    const endDate: Moment = moment(shifts.endDate, dateFormat, STRICT_MODE).add(
This offset is made so that when we compare `startTime` to `endDate`, any time block that starts and ends on the original endDate will be added to `shiftTimes`. For example, if our end date is 2022-01-01, a time block that starts on that same day (2022-01-01) will be added as it passes the `start < endDate` check.

2022-01-09 21:56 UTC, lambo-liu commented on backend/services/implementations/shiftService.ts
> +          let start = startTime.clone(), end = endTime;
We're setting `start` to the value of `startTime` (hence cloning `startTime`) here because we're using `start` as an iterator to the for loop.

2022-01-09 21:58 UTC, lambo-liu commented on backend/services/implementations/shiftService.ts
> +  async checkConflictingShifts(
I asked product peops last month and they were OK with overlapping shift times 👍

2022-01-11 18:41 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +  async checkConflictingShifts(
> Not sure what is more efficient but we can also add an index to the database so that postingId, startTime, and endTime are unique.

I like this idea. My feeling is that even with the write overhead of indexing, it might be more performant as it wouldn't require querying all shifts of a posting and then comparing start/end times for every shift write.

Would suggest merging this current implementation first though and doing some experiments before committing to the index approach.

2022-01-11 18:43 UTC, sherryhli commented on backend/services/implementations/shiftService.ts
> +          let start = startTime.clone(), end = endTime;
I think it's safe to not clone `startTime` but I wasn't 100% sure, @lambo-liu can you confirm?

2022-01-11 18:45 UTC, sherryhli commented
> The insert for postings in this PR description is out of date right? I tried running it and the table no longer has some of these colums.

@LenaNguyen this is the updated insert:
```sql
INSERT INTO postings (branch_id, type, title, description, num_volunteers, auto_closing_date, start_date, end_date) VALUES (1, 'GROUP', 'Title', 'Description', 5, '2021-01-01', '2021-01-11', '2021-01-15');
```

Could you take a final pass at this PR, I think it's good to go :)

2022-01-11 18:48 UTC, sherryhli approved these changes
LGTM but let's hold off on merging until Lena approves

2022-01-11 21:10 UTC, LenaNguyen approved these changes
Looks good :))

2022-01-11 21:20 UTC, merged