Remove user panel mutation + fix panel UI overflow
uwblueprint/sistering pull request #580
Opened 2022-08-12 04:28 UTC by lambo-liu

## Ticket link

Closes #415 
Closes #574 

## Implementation description
* Modified prisma schema to cascade delete a user's signups.
* Hooked up the "Remove user" button with the remove volunteer/admin mutation depending on the user's role
* IMPORTANT: Do NOT delete a seed user! The remove user mutation also removes them from Firebase.
* Refetched table when a user is removed.
* Fixed UI overflow on side panel when many tags are present.

## Steps to test
1. Run `npx prisma migrate dev` for the latest table changes
2. Create a new admin or volunteer account (Do not use seed accounts!!)
3. Remove the user using a super admin account
4. Check that the user is removed from SQL tables and Firebase

## What should reviewers focus on?
* Correct prisma schema updates

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-12 22:32 UTC, MatoPlus commented on frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
> +  const { loading, error, refetch } = useQuery(USERS, {
Let's avoid drilling and use the `refetchQueries` option for mutations for auto-refetch.

2022-08-12 22:33 UTC, MatoPlus commented on frontend/src/components/admin/users/ProfileDrawer.tsx
> +  );
```suggestion
  const [deleteUserByEmail] = useMutation(
    isVolunteer
      ? DELETE_VOLUNTEER_USER_BY_EMAIL
      : DELETE_EMPLOYEE_USER_BY_EMAIL,
          {
      refetchQueries: [
        "AdminUserManagementPage_Users",
      ],
    },
  );
```

2022-08-12 23:04 UTC, MatoPlus commented on frontend/src/components/pages/admin/user/AdminUserManagementPage.tsx
> +  const { loading, error, refetch } = useQuery(USERS, {
I've tested the current implementation with drilling and it doesn't seem like the user data is updated until page refresh

2022-08-12 23:05 UTC, MatoPlus requested changes
Made some suggestions. Tested, works as intended. Should be good to merge

2022-08-13 02:03 UTC, lambo-liu commented on frontend/src/components/admin/users/ProfileDrawer.tsx
> +  );
Good call! Made the changes, feel free to take another look.

2022-08-13 14:07 UTC, MatoPlus approved these changes
LTGM, thanks for getting this done!

2022-08-13 17:42 UTC, merged