Fixed non aligned tags in account forms
uwblueprint/sistering pull request #589
Opened 2022-08-13 23:32 UTC by eevanwong

…r and admin account forms

## Ticket link

Closes #561 

## Steps to test
1. Go to volunteer account, check edit account profile
2. Go to admin account , check edit account profile
3. Check admin and volunteer create account forms

Volunteer Account Form
![image](https://user-images.githubusercontent.com/71536798/184516538-50417b79-61e4-442f-ac06-81cfb87964e4.png)

Employee Account Form
![image](https://user-images.githubusercontent.com/71536798/184516563-e4fcd92e-85b2-40e9-9b57-aade4fda269c.png)

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-14 00:07 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
>                />
```suggestion
              />
<Box />
```

2022-08-14 00:08 UTC, MatoPlus commented on frontend/src/components/user/AccountForm.tsx
> +                <Box />
Can we just always render an empty box before to avoid this ternary?

2022-08-14 00:10 UTC, MatoPlus requested changes
LGTM with suggestion

2022-08-15 18:53 UTC, eevanwong commented on frontend/src/components/user/AccountForm.tsx
>                />
Yep you're correct. This is better than what I originally had.

2022-08-16 00:27 UTC, MatoPlus approved these changes
LGTM

2022-08-16 15:56 UTC, merged