Boya/skill tag and plural posting card
uwblueprint/sistering pull request #596
Opened 2022-08-14 02:15 UTC by Boyazhang1

## Ticket link

Closes #

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-16 01:34 UTC, neelismail01 requested changes

2022-08-16 01:34 UTC, neelismail01 commented on frontend/yarn.lock
> +  integrity sha512-ZN61ockLaIAiiPbZfMKT2S03nbWx28OHg/nAiDnNfmN4QmAMcdwVajPn2QQwnNVGAr4jS4nbhbYzCcjq8livXQ==
Could you revert these changes before merging?

2022-08-16 01:34 UTC, neelismail01 commented on frontend/package.json
> +    "@tanstack/react-table": "^8.5.11",
Was the change in package version necessary for this PR?

2022-08-16 01:34 UTC, neelismail01 commented on docker-compose.yml
> +      test: ['CMD-SHELL', 'pg_isready -U postgres']
Could you revert these changes to keep our Docker files consistent?

2022-08-16 01:34 UTC, neelismail01 commented on backend/Dockerfile
> +EXPOSE 5555
Could you revert this file as well for consistency?

2022-08-16 06:25 UTC, Boyazhang1 commented on frontend/package.json
> +    "@tanstack/react-table": "^8.5.11",
oh I think that auto updated when I did yarn add lol, I'll manually revert it back

2022-08-16 21:21 UTC, sherryhli commented on frontend/package.json
> +    "@tanstack/react-table": "^8.5.11",
Could we revert the corresponding changes in yarn.lock as well?

2022-08-16 22:39 UTC, MatoPlus commented on frontend/src/components/admin/AdminPostingCard.tsx
> +                : `${numVolunteers} volunteer${numVolunteers > 1 ? "s" : ""}`}
```suggestion
                : `${numVolunteers} volunteer${numVolunteers != 1 ? "s" : ""}`}
```
edge case for num = 0 (0 volunteers)

2022-08-16 22:40 UTC, MatoPlus commented on frontend/src/components/common/TagsPopover.tsx
> +  height,
lint

2022-08-16 22:41 UTC, MatoPlus requested changes
Looks good aside from some suggestions

2022-08-18 00:42 UTC, MatoPlus approved these changes
LGTM, thanks for getting this done!

2022-08-18 01:28 UTC, merged