Add branch tags to edit profile page
uwblueprint/sistering pull request #608
Opened 2022-08-16 04:09 UTC by lambo-liu

## Ticket link

Closes #599 

## Implementation description
* Added user branch tags to the edit profile page
* Fixed existing React warning with invalid date format

## Steps to test
1. Navigate to `http://localhost:3000/edit-account`, the user's branches should show at the top:
<img width="1440" alt="Screen Shot 2022-08-16 at 12 07 12 AM" src="https://user-images.githubusercontent.com/47638847/184796011-a95db0d6-2fd9-477a-ae18-7f2419371fbf.png">

## What should reviewers focus on?
* N/A

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-16 21:16 UTC, sherryhli requested changes
A couple of minor things

2022-08-16 21:16 UTC, sherryhli commented on frontend/src/components/pages/EditAccountPage.tsx
> +  console.log(user);
Please delete

2022-08-16 21:16 UTC, sherryhli commented on frontend/src/components/pages/EditAccountPage.tsx
> +              >
1. I know there are no designs for this but for consistency, could we use the brand variant without overriding any styling?
2. The key prop should probably be unique, let's use `branch.id`

2022-08-16 21:17 UTC, sherryhli commented on frontend/src/components/pages/EditAccountPage.tsx
> +                ? moment(user?.dateOfBirth).format("YYYY-MM-DD")
Nit: optional chaining not needed anymore

```suggestion
                ? moment(user.dateOfBirth).format("YYYY-MM-DD")
```

2022-08-16 22:30 UTC, lambo-liu commented on frontend/src/components/pages/EditAccountPage.tsx
> +                ? moment(user?.dateOfBirth).format("YYYY-MM-DD")
I added this ternary statement because `user.dateOfBirth` can be null, and so moment complains in the dev console when it receives null as a parameter. Should I still change this?

2022-08-16 23:49 UTC, sherryhli reviewed
LGTM but will leave it to @MatoPlus to give the final approval on look and feel since he opened the issue :)

2022-08-17 00:57 UTC, MatoPlus approved these changes
LGTM. Thanks for getting this done!

2022-08-17 01:10 UTC, merged