Update getShiftSignupForUser to only return signups for current postings
uwblueprint/sistering pull request #609
Opened 2022-08-18 01:46 UTC by MatoPlus

## Ticket link

Closes #604 

## Implementation description
* Update getShiftSignupsForUser query to only query for signups for postings that have not ended yet. We do not have any usage of this query that needs expired signups.

## Steps to test
1. Do this locally where you have direct access to change the DB records
2. Login as a volunteer
3. Sign up for 3 signups
4. Go to DB and put signup for PUBLISHED, CANCELLED, and PENDING, one for each. They should appear in volunteer homepage signups tab
5. GO to DB and put posting endate to a date in the past
6. The signups for volunteer should no longer be visible
7. Similarly they should not be visible on schedule review page - volunteer profile page

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-18 22:02 UTC, sherryhli requested changes

2022-08-18 22:02 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +                  endDate: { gt: new Date() },
I suspect there might be an edge case due to how we handle timezones. Running this query between 8pm-12am EDT (or 7pm-12am EST) will exclude postings that end on the current day (Eastern time). Let's verify if this is indeed the case and then fix. Suggested solution (pseudocode):

```suggestion
                  endDate: { gt: moment.isDST() ? new Date() - UTC_EDT_OFFSET : new Date() - UTC_EST_OFFSET },
```

**Context:** Our application generally ignores timezones and stores all dates as UTC and interpret them as Toronto local time[^1]. This approach is meant to simplify handling of daylight savings toggling on and off[^2]. Between the time periods mentioned above, `new Date()` would return a time value that's already in the "next" day according to UTC, which ends up excluding postings that end on the current day according to Eastern time.

Let me know if this doesn't make sense 😅 

[^1]: 2022-08-18 00:00 UTC in the database is interpreted as 2022-08-18 00:00 E**D**T by the application, while 2022-12-18 00:00 UTC is interpreted as 2022-12-18 00:00 E**S**T
[^2]: For example, a shift that is created in the summer with start date of 3pm will continue to start at 3pm after end of daylight savings. It will not automatically change to 2pm.

2022-08-18 22:02 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +          AND: [
Is `AND` a binary operator? Could we include the end date condition as part of the `filter` above?

2022-08-18 23:02 UTC, MatoPlus commented on backend/services/implementations/shiftSignupService.ts
> +                  endDate: { gt: new Date() },
will look into it 👍

2022-08-19 02:31 UTC, MatoPlus commented on backend/services/implementations/shiftSignupService.ts
> +                  endDate: { gt: new Date() },
tried to resolve. lmk if solution is sketchy : )

2022-08-19 02:31 UTC, MatoPlus commented on backend/services/implementations/shiftSignupService.ts
> +                  endDate: { gt: new Date() },
pre-patch while testing, I also did run into the issue that was described. good catch

2022-08-19 03:59 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +                  endDate: { gt: new Date() },
Looks good, thanks for addressing!

2022-08-19 03:59 UTC, sherryhli approved these changes
🚢

2022-08-19 17:52 UTC, merged