Add VolunteerUser CRUD Methods
uwblueprint/sistering pull request #63
Opened 2021-12-04 19:11 UTC by jiarucao

## Ticket link

Closes #29 

## Implementation description
* 

## Steps to test
1.

## What should reviewers focus on?
* 

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-12-07 00:19 UTC, sherryhli reviewed
Some general questions around the use of Prisma's `include`, will do a more thorough review once that's clarified. Thanks!

2021-12-07 00:19 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +        },
```suggestion
        include: {
          branches: true,
          skills: true,
          user: true,
        },
```

Can we include user here? Should avoid doing two separate queries to the two tables, retrieving a volunteer user is a single unit of work

2021-12-07 00:19 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +          const user = await this.getUserById(String(v.id));
Shouldn't `volunteers` already contain the corresponding users' data because of the `include`? Why is the separate lookup necessary?

2021-12-07 03:48 UTC, sherryhli requested changes
Great work so far! Will do a second pass once this batch of comments are addressed.

2021-12-07 03:48 UTC, sherryhli commented on backend/graphql/index.ts
> +  scalar Date
Can we define custom scalar logic to parse YYYY-MM-DD as a date? The time portion of the date isn't necessary for values like birth date and hire date. We can define another `DateTime` scalar for cases that do require the time.

Example: https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/#example-the-date-scalar

cc @lambo-liu I think we can move date format validation checks in `ShiftService` into the custom scalar `parseValue` method. Can do that in a separate PR though, no need to address it in #55 :)

2021-12-07 03:48 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +        },
As mentioned in [Slack](https://uwblueprint.slack.com/archives/C02K4KBEQVC/p1638844668006500?thread_ts=1638836823.005800&cid=C02K4KBEQVC), let's use `include` wherever applicable :)

2021-12-07 03:48 UTC, sherryhli commented on backend/graphql/types/userType.ts
> +    branches: [BranchInput]
I don't think custom input types are necessary (the names are never used), both can be just arrays of `ID`s

2021-12-08 00:07 UTC, sherryhli reviewed
A couple more things, some comments might apply to more than one spot so please address all similar issues. Thanks! 🙏

2021-12-08 00:07 UTC, sherryhli commented on backend/graphql/resolvers/userResolvers.ts
> +    },
GraphQL best practice is to always return a value from operations so for deletions, let's return the ID of the deleted item.   Unfortunately starter code did not follow this convention 😅

2021-12-08 02:58 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +              set: [], // setting the related branches to be [] before connecting the passed in values
cc @albertlai431 @briantu

2021-12-15 02:11 UTC, sherryhli requested changes

2021-12-15 02:11 UTC, sherryhli commented on backend/graphql/index.ts
> +    return value.getTime(); // value for server
Would like return value to be YYYY-MM-DD string

2021-12-15 02:11 UTC, sherryhli commented on backend/graphql/index.ts
> +    }
```suggestion
    if (ast.kind === Kind.STRING) {
      // insert same code from parseValue
    }
```

2021-12-15 02:11 UTC, sherryhli commented on backend/graphql/index.ts
> +    return null;
Please throw exception

2021-12-17 00:14 UTC, sherryhli requested changes
Tested and the API works as expected! 🎉

Just added some minor comments, mostly around code clean up and styling.

2021-12-18 19:01 UTC, daniel-sm-yu commented on backend/graphql/types/userType.ts
> +    role: Role!
also removed `role` in `UpdateVolunteerUserDTO`

2021-12-18 20:37 UTC, daniel-sm-yu commented on backend/graphql/index.ts
> +  return dateObj.toISOString().slice(0, 10) === dateString;
we ended up changing the function to:
```
const isValidDate = (dateString: string) => {
  const regEx = /^\d{4}-\d{2}-\d{2}$/; // YYYY-MM-DD
  if (!dateString.match(regEx)) return false; // Invalid format
  return (
    !Number.isNaN(Date.parse(dateString)) && // cover cases of DD > 31
    new Date(dateString).toISOString().slice(0, 10) === dateString // cover cases of DD <= 31
  );
};
```
we noticed that js's Date handled DD of a month exceeding the actual number of days in that month in 2 ways:

if DD > 31, result is `NaN`
if DD <= 31, result is "rolled forward", for example, Apr 31 becomes May 1 (since Apr has 30 days)

so the 2 conditions we check for explicitly covers the 2 cases

2021-12-18 20:50 UTC, daniel-sm-yu commented on backend/prisma/schema.prisma
> +  user            User                      @relation(fields: [id], references: [id])
In deleteVolunteerUserById:
```
            volunteer: {
              update: {
                branches: {
                  set: [],
                },
                skills: {
                  set: [],
                },
              },
              delete: true, // this was doing the cascade behaviour
```

2021-12-18 20:51 UTC, daniel-sm-yu commented on backend/prisma/schema.prisma
> +  user            User                      @relation(fields: [id], references: [id])
Jiaru tested and found that
```
  user            User                      @relation(fields: [id], references: [id], onDelete: Cascade)
```
does the same thing so we changed it to this

2021-12-19 00:03 UTC, sherryhli commented on backend/graphql/index.ts
> +  return dateObj.toISOString().slice(0, 10) === dateString;
Gotcha, thanks for explaining!

2021-12-19 03:17 UTC, sherryhli submitted a review, later dismissed
LGTM 🚢! I've approved but please make sure to rebase[^1] on `main` and resolve conflicts before merging. Left a couple of nits, would be great if you can sneak those changes in as well 😄

> 1. Rebase on `main`, resolve merge conflicts in `schema.prisma` and elsewhere
> 2. Discard the original migration files that were added as part of the PR
> 3. Regenerate a single new migration file

**Please also take note of this [reminder](https://uwblueprint.slack.com/archives/C02CN0ZAZDG/p1639610746013600) about .env changes after updating your branch.**

[^1]: I recommend squashing all commits before rebasing. Alternatively you can merge `main` instead of rebasing, though my personal preference is rebase.

2022-01-21 03:23 UTC, sherryhli approved these changes
LGTM! 🚢 No need to address any of the comments right now

2022-01-21 03:23 UTC, sherryhli commented on backend/prisma/schema.prisma
> +  user     User      @relation(fields: [id], references: [id], onDelete: Cascade)
I think `userId` is no longer needed, can remove as part of the Employee CRUD PR though

2022-01-21 03:23 UTC, sherryhli commented on backend/prisma/schema.prisma
> +}
Nit: trailing newline

2022-01-21 03:23 UTC, sherryhli commented on backend/services/implementations/authService.ts
> +    } catch (error: any) {
Nit: can type as `unknown` instead, we can address this separately as it affects a lot of try-catch blocks in the code

2022-01-21 03:23 UTC, sherryhli commented on backend/services/implementations/userService.ts
> +import { PrismaClient, User, Volunteer, Skill, Branch } from "@prisma/client";
Nit: can remove unused import

2022-01-21 05:01 UTC, sherryhli reviewed
Missed a few minor things in my last review, sorry about that!

2022-01-21 05:01 UTC, sherryhli commented on backend/types.ts
> -
Keep

2022-01-21 05:01 UTC, sherryhli commented on backend/types.ts
> +export type SkillRequestDTO = Omit<SkillResponseDTO, "id">;
Delete

2022-01-21 15:38 UTC, jiarucao commented on backend/prisma/schema.prisma
> +  id              Int                       @unique @id
Yep this is redundant, do you want me to remove it in this PR? @sherryhli

2022-01-21 16:34 UTC, sherryhli approved these changes

2022-01-21 19:05 UTC, sherryhli commented on backend/prisma/schema.prisma
> +  id              Int                       @unique @id
Let's keep it for now, can lump it together with any schema changes needed for the Employee PR. Go ahead and 🚢!

2022-01-22 03:50 UTC, merged