Fix admin posting card event date range
uwblueprint/sistering pull request #635
Opened 2022-08-21 20:24 UTC by briantu

## Ticket link

Closes #616

## Implementation description
* Fixed admin posting card to only show single date if posting is an event
* Fixed time range in volunteer posting card to show correct time (was offset by 4 hours the posting shift times)

## Steps to test
1. Go to `http://localhost:3000/admin`
2. Create event posting
3. Check posting card date is not shown as range anymore
4. Check volunteer posting card time range is correct

## What should reviewers focus on?
* Code correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-21 20:26 UTC, briantu commented on frontend/src/utils/DateTimeUtils.ts
> +  return moment(date).format("h:mma");
Not sure if this is the correct fix because iirc I thought we are using UTC?

2022-08-21 20:40 UTC, MatoPlus commented on frontend/src/utils/DateTimeUtils.ts
> +  return moment(date).format("h:mma");
yea im reworking this as well, you can leave this to me if you want: https://github.com/uwblueprint/sistering/pull/633

2022-08-21 20:42 UTC, MatoPlus reviewed
seems good to me. Will approve in a bit after some tests

2022-08-21 20:45 UTC, briantu commented on frontend/src/utils/DateTimeUtils.ts
> +  return moment(date).format("h:mma");
Sure, will leave it to you

2022-08-21 20:48 UTC, MatoPlus commented on frontend/src/utils/DateTimeUtils.ts
> +  return moment(date).format("h:mma");
Awesome, please revert this. seems like a few usage break due to the change 😢. gotta be more granular with the change

2022-08-22 00:05 UTC, MatoPlus commented on frontend/src/components/pages/admin/AdminHomepage.tsx
> +                      type={
Why do we need to drill this? Would it be okay to move this into `getPostingDateRange` logic?

2022-08-22 00:06 UTC, MatoPlus requested changes
Made 2 suggestions, LGTM otherwise

2022-08-22 00:42 UTC, briantu commented on frontend/src/components/pages/admin/AdminHomepage.tsx
> +                      type={
Sure, I can do that

2022-08-22 18:59 UTC, MatoPlus approved these changes
LGTM!

2022-08-22 19:17 UTC, merged