Only show volunteer posting details if user in branch
uwblueprint/sistering pull request #637
Opened 2022-08-21 23:26 UTC by briantu

## Ticket link

Closes #612

## Implementation description
* If volunteer is not in posting branch, then redirect to not found page

## Steps to test
1. Log in as volunteer
2. Try to see posting details for branch current volunteer is not in
3. Check you are redirected to not found page

## What should reviewers focus on?
* Code correctness

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-21 23:28 UTC, briantu commented
This fix works, but not sure if it's the best way to do it cuz it's a bit messy. Lmk if this is okay - if it is, then I'll also do it for the volunteer posting availabilities page!

2022-08-22 00:12 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +  }, [postingDetails]);
hmm what are we trying to do here? It seems a bit unintuitive to me.

2022-08-22 00:15 UTC, MatoPlus reviewed
hmm would it make more sense to do this on the server side instead? ie: for the posting query, if the current user is a volunteer, make sure the posting is in the same branch as the volunteer, otherwise, on error we redirect instead of showing a toast @briantu would that be better?

2022-08-22 00:38 UTC, briantu commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +  }, [postingDetails]);
ah yeah that's my way of checking when `userBranches` and `postingDetails` have updated cuz the first time UseEffect runs they are both the initial value so im waiting until the 2nd update which is when they finished loading, and I need to know when they are finished loading otherwise it's a pain handling when they are null and not null and stuff

2022-08-22 00:40 UTC, briantu commented
> hmm would it make more sense to do this on the server side instead? ie: for the posting query, if the current user is a volunteer, make sure the posting is in the same branch as the volunteer, otherwise, on error we redirect instead of showing a toast @briantu would that be better?
Wait yeah that sounds like a better solution

2022-08-22 15:13 UTC, MatoPlus requested changes
as discussed let's fix the visibility of the posting resolver for volunteers in this PR instead. you can look at the `postings` resolver as an example as I believe that already has filtering.


That was done here: https://github.com/uwblueprint/sistering/pull/584/files#diff-1df777bf9199297d8db41bd9b2be9de9ada51c8ed623879ac6a51a11db1253fdR160-R176

2022-08-22 21:41 UTC, MatoPlus commented on frontend/src/components/pages/volunteer/posting/VolunteerPostingDetails.tsx
> +  return (!loading && !postingDetails) || error ? (
```suggestion
  return (!loading && !postingDetails) || postingDetailError ? (
```
maybe make this more explicit?

2022-08-22 21:42 UTC, MatoPlus commented on backend/graphql/resolvers/postingResolvers.ts
> +      { id, userId }: { id: string; userId?: string },
I wonder if we can use the auth token to get the user id somehow. cuz `userId` field is pretty arbitrary (i can just pass it in for whatever user)

2022-08-22 21:43 UTC, MatoPlus commented on backend/services/implementations/postingService.ts
> +      }
this logic only applies for volunteers right?

2022-08-22 23:52 UTC, briantu commented on backend/graphql/resolvers/postingResolvers.ts
> +      { id, userId }: { id: string; userId?: string },
Yes, we can

2022-08-22 23:53 UTC, briantu commented on backend/services/implementations/postingService.ts
> +      }
Will be checking using auth token method now, so logic will explicitly check for volunteers

2022-08-23 15:22 UTC, MatoPlus approved these changes
LGTM, thanks for getting this done!

2022-08-23 15:25 UTC, MatoPlus commented on backend/graphql/resolvers/postingResolvers.ts
> +      context: ExpressContext,
nit:
```suggestion
      { req }: { res: Response },
```
we can only pass in what we need

2022-08-23 18:52 UTC, briantu commented on backend/graphql/resolvers/postingResolvers.ts
> +      context: ExpressContext,
I originally tried that, but I got some type error when I did `getAccessToken(req)`, but doing `getAccessToken(context.req)` worked.

2022-08-23 18:53 UTC, merged