Create Posting CRUD Methods and GraphQL Resolvers
uwblueprint/sistering pull request #64
Opened 2021-12-04 19:55 UTC by albertlai431

## Ticket link

Closes #50 

## Implementation description
- Implement CRUD methods:
  - getPosting
  - getPostings
  - createPosting
  - updatePosting
  - deletePosting
- Create corresponding GraphQL resolvers and DTOs
- Modified Prerequisites Model in schema as requested in ticket and generated associated prisma migration file 

## Steps to test
1. Start docker and run `docker-compose up --build`
2. We need row(s) in the skills, branches, and employees tables for testing and will need to create those with raw SQL for now. Run the following commands:
```bash
docker exec -it sistering_db /bin/bash
psql -U postgres -d sistering
INSERT INTO branches (name) VALUES ('Branch1');
INSERT INTO skills (name) VALUES ('Skill1');
INSERT INTO employees (userId, branch_id) VALUES ('1','1');
```
3. Run `docker exec -it sistering_backend /bin/bash -c "npx prisma generate"` and run the lastest migration files using `npx prisma migrate deploy`
4. Go to http://localhost:5000/graphql and verify that all GraphQL queries and mutations introduced in this ticket work as expected

## What should reviewers focus on?
* Verify that GraphQL endpoints work as expected

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2021-12-08 03:11 UTC, sherryhli requested changes
Looking good so far! Will do a second review once this set of comments is addressed

2021-12-08 03:11 UTC, sherryhli commented on backend/services/implementations/postingService.ts
> +            }),
Please see this [comment](https://github.com/uwblueprint/sistering/pull/63/files#r764513528) in @jiarucao and @daniel-sm-yu's PR, will need to clear existing records in the join tables before connecting with the new ids

2021-12-08 03:11 UTC, sherryhli commented on backend/services/implementations/postingService.ts
> +      const deleteResult: Posting | null = await prisma.posting.delete({
The delete needs to be cascaded to all associated shifts
https://www.prisma.io/docs/concepts/components/prisma-schema/relations/referential-actions

2021-12-08 03:11 UTC, sherryhli commented on backend/prisma/schema.prisma
> +  role      Role
Nit: can we revert all pure formatting changes in this file? It'll prevent some annoying merge conflicts for the others who are also modifying things here

2021-12-08 03:11 UTC, sherryhli commented on backend/prisma/schema.prisma
> +// model PostingOnSkill {
Let's delete everything that's commented out

2021-12-11 01:14 UTC, briantu commented on backend/services/implementations/postingService.ts
> +function validateDate(date: string) {
Got it, I'll keep it like this for now then.

2021-12-11 01:14 UTC, briantu commented on backend/services/implementations/postingService.ts
> +        postings.map(async (posting: PostingWithRelations) => {
You're right, fixed!

2021-12-11 01:17 UTC, briantu commented on backend/prisma/schema.prisma
> +  role      Role
I think the current formatting changes follow Prisma's format. There is a `prisma format` command which I ran, and nothing was changed in this file. I think maybe we keep it like this and stay consistent with this Prisma's style of formatting?

2021-12-13 01:22 UTC, sherryhli requested changes
Almost there, just a couple of minor things left!

2021-12-13 01:22 UTC, sherryhli commented on backend/prisma/schema.prisma
> +  name       String
Why was the unique constraint removed?

2021-12-13 01:22 UTC, sherryhli commented on backend/prisma/schema.prisma
> +  role      Role
Yep, definitely want to keep to this format eventually! Just thought it'd make things easier for Jiaru and Daniel in terms of merge conflicts in the meantime (they are also modifying this file in their PR).

But yeah, on second thought it shouldn't be too bad to deal with. Let's keep it 👍

2021-12-16 22:00 UTC, sherryhli approved these changes
LGTM! 🚢
(please coordinate the order of merging with the rest of the team as described in [Slack](https://uwblueprint.slack.com/archives/C02CN0ZAZDG/p1639538084009000))

2021-12-18 03:23 UTC, sherryhli commented
Extra nit: can we rename these files to keep consistency with the other interface files?

`backend/services/interfaces/IPostingService.ts` -> `backend/services/interfaces/postingService.ts`
`backend/services/interfaces/ISkillService.ts` -> `backend/services/interfaces/skillService.ts`
`backend/services/interfaces/IEntityService.ts` -> `backend/services/interfaces/entityService.ts`

2021-12-18 18:31 UTC, briantu approved these changes

2021-12-18 18:31 UTC, merged