Add a refetch query to admin invite mutation :sparkles:
uwblueprint/sistering pull request #641
Opened 2022-08-22 23:30 UTC by AdrianaCeric

## Ticket link

Closes #630 

## Implementation description
* Added a refetch query to admin invite mutation

## Steps to test
1. Invite a super admin and check if invite can be viewed without having to refresh page

## What should reviewers focus on?
* Correctness 

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-08-22 23:49 UTC, MatoPlus requested changes
Idea looks good, we need this for the `AddVolunteerModal` as well

2022-08-22 23:49 UTC, MatoPlus commented on frontend/src/components/admin/AddAdminModal.tsx
> +    refetchQueries: ["GET_USER_INVITE"],
```suggestion
    refetchQueries: ["UserInvitesModal_getUserInvites"],
```

right idea but referring to the wrong graphql query name

2022-08-23 00:09 UTC, AdrianaCeric commented on frontend/src/components/admin/AddAdminModal.tsx
> +    refetchQueries: ["GET_USER_INVITE"],
thanks for feedback!

2022-08-23 00:34 UTC, MatoPlus approved these changes

2022-08-23 01:04 UTC, merged