Built out shift signup endpoints
uwblueprint/sistering pull request #90
Opened 2022-01-16 20:52 UTC by hujoseph99

## Ticket link

Closes #54

## Implementation description
* Defined `CreateShiftSignupRequestDTO`, `UpdateShiftSignupRequestDTO`, `ShiftSignupResponseDTO` types
* Implemented the following CRUD endpoints with their corresponding graphql queries and mutations:
  * `createShiftSignups`
  * `updateShiftSignup`
  * `getShiftSignupsForUser` 
* Prisma schema changes (with corresponding migrations):
  * Added `note` varchar to `Signup` prisma model
  * Added foreign key constraint to `userId` in `Signup` model.
  * Added a unique key constraint to for `shiftId` and `userId` pair in `Signup` model

## Steps to test
1. Ensure that the docker containers are up and running
2. Run prisma `migration` and `generate` commands
2. Ensure that you have test data in the following tables: `users`, `shifts`, `postings`, `branches`.
  - If you don't have data, these commands might be helpful for getting some in easily:
  - Through the Postgres CLI:
    - `insert into branches (id, name) values (1, 'test branch');`
    - `insert into postings (id, branch_id, type, title, description, auto_closing_date, start_date, end_date) values (1, 1, 'GROUP', 'a', 'a', '2022-01-09T21:33:51.302Z', '2022-01-09T21:33:51.302Z', '2022-01-09T21:33:51.302Z');`
  - Through graphql interface (`localhost:5000/graphql`):
    - `mutation { createShifts(shifts: { postingId: "1", times: [ { date: "2021-12-16" startTime: "01:30" endTime: "04:30" }, { date: "2021-12-18" startTime: "12:00" endTime: "16:00" } ], endDate: "2022-01-15", recurrenceInterval: BIWEEKLY }) { id postingId startTime endTime } }`
  - Credits to @lambo-liu in #55 
4. Go to `localhost:5000/graphql` and test the following new endpoints: `createShiftSignups`, `updateShiftSignup`, and `getShiftSignupsForUser`.  The following are some query/mutations that I wrote in my own testing that you might be able to use:
```
query {
  getShiftSignupsForUser(userId: "2") {
    shiftId,
    userId,
    numVolunteers,
    note,
    status
  }
}

mutation {
  createShiftSignups (shifts: [
    {
      shiftId: 2,
      userId: 2,
      numVolunteers: 3,
      note: "test"
    }
  ]) {
    shiftId,
    userId,
    numVolunteers,
    note
  }
}

mutation {
  updateShiftSignup (
    shiftId: "2",
    userId: "2",
    update: {
      status: CONFIRMED,
      note: "test",
      numVolunteers: 3
    }
  ) {
    shiftId,
    userId,
    numVolunteers,
    note,
    status
  }
}
```

## What should reviewers focus on?
* Ensure that it works for edge cases like duplicating shift signups, signing up for a shift that doesn't exist, a user that doesn't exist signing up for a shift, etc.
* General testing for basic features

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-01-26 18:47 UTC, LenaNguyen submitted a review, later dismissed
Just wait for this comment to be addressed. Everything looks great!

![](https://media.giphy.com/media/zfYpmAfrcVOAE/giphy.gif)

2022-01-26 18:47 UTC, LenaNguyen commented on backend/services/implementations/shiftSignupService.ts
> +  async createShiftSignups(
@sherryhli @JoshuaYe are we allowing non-volunteer roles to be added to shifts as well? Otherwise we should add a check for their role.

2022-01-26 19:32 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +  async createShiftSignups(
To my knowledge, non-volunteers should **not** be able to sign up, so checking would be a good idea. I wonder if we can perform the check in the authorization layer instead though (assuming we don't have a case where an admin is able to sign up on behalf of a volunteer). This saves a lookup query to find the role of the user.

2022-01-26 19:51 UTC, sherryhli requested changes
Just jumping in to point out a small issue with the order of migrations 🙂

2022-01-26 19:51 UTC, sherryhli commented on backend/prisma/migrations/20220121012944_add_volunteer_users/migration.sql
> -
Was this deletion autogenerated? We shouldn't ever be modifying existing migration files as it will break our deployed environments.

2022-01-26 19:51 UTC, sherryhli commented on backend/prisma/migrations/20220116032551_add_note_to_signup/migration.sql
> +/*
Can you please update the timestamp in the migration folder name to be after `20220121012944`, which is the last migration to run in the staging environment? Otherwise the 2 signup table migrations will not run at all.

2022-01-26 19:51 UTC, sherryhli commented on backend/prisma/migrations/20220116173256_added_unique_and_forign_key_contraints_to_signup/migration.sql
> +ALTER TABLE "signups" ADD CONSTRAINT "signups_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
Please update the timestamp of this migration's folder as well. After doing that, this line here should no longer be necessary as the FK would have been added as part of `backend/prisma/migrations/20220121012944_add_volunteer_users/migration.sql`

2022-01-26 19:51 UTC, sherryhli commented on backend/prisma/schema.prisma
> +  @@unique([shiftId, userId])
Thoughts about making `[shiftId, userId]` the PK of this table?

2022-01-26 20:10 UTC, JoshuaYe commented on backend/services/implementations/shiftSignupService.ts
> +  async createShiftSignups(
Sherry is correct. If a volunteer has not requested a shift, they cannot be assigned to it by an admin. This was confirmed by Aoife in our last client meeting.

2022-01-26 20:18 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +  async createShiftSignups(
Got it, thanks @JoshuaYe! In that case I think handling it with the authorization middleware would be perfect, we check that the `CreateShiftSignups` mutation can only be invoked by a user with the VOLUNTEER role, and that a user can only sign themselves up (i.e. userId in request body === userId corresponding to access token)

2022-01-29 22:03 UTC, hujoseph99 commented on backend/services/implementations/shiftSignupService.ts
> +  async createShiftSignups(
Updated

2022-01-29 22:04 UTC, hujoseph99 commented on backend/prisma/migrations/20220121012944_add_volunteer_users/migration.sql
> -
Sorry, this was my misunderstanding with migrations. I've fixed it now

2022-01-29 22:04 UTC, hujoseph99 commented on backend/prisma/migrations/20220116032551_add_note_to_signup/migration.sql
> +/*
Updated

2022-01-29 22:04 UTC, hujoseph99 commented on backend/prisma/migrations/20220116173256_added_unique_and_forign_key_contraints_to_signup/migration.sql
> +ALTER TABLE "signups" ADD CONSTRAINT "signups_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
Updated

2022-01-29 22:04 UTC, hujoseph99 commented on backend/prisma/schema.prisma
> +  @@unique([shiftId, userId])
I think it makes sense, I've made the changes

2022-01-29 22:07 UTC, hujoseph99 commented
Sorry for the late response, I've been busy these past two days. I've made the changes now!

2022-01-30 20:33 UTC, LenaNguyen requested changes

2022-01-30 20:33 UTC, LenaNguyen commented on backend/graphql/index.ts
> +const authorizedByVolunteer = () => isAuthorizedByRole(new Set(["VOLUNTEER"]));
we also want to check `isAuthorizedByUserId` here to check that the userid in the token is the same as the userid they are signingup the shift as

2022-01-30 21:01 UTC, hujoseph99 commented on backend/graphql/index.ts
> +const authorizedByVolunteer = () => isAuthorizedByRole(new Set(["VOLUNTEER"]));
Added!

2022-01-30 21:39 UTC, sherryhli requested changes

2022-01-30 21:39 UTC, sherryhli commented on backend/prisma/migrations/20220116032551_add_note_to_signup/migration.sql
> +/*
With #106 just merged the latest migration timestamp is now `20220128011600` (January 28, 2022), could you please update this file name again?

2022-01-30 21:39 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +    }
For type-safe error handling, please use `getErrorMessage` from utilities/errorUtils.ts

```suggestion
    } catch (error: unknown) {
      Logger.error(`Failed to shift signups. Reason = ${getErrorMessage(error)}`);
      throw error;
    }
```

2022-01-30 21:39 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +        shiftSignups?.map((shiftSignup) =>
```suggestion
        shiftSignups.map((shiftSignup) =>
```

Do we need optional chaining here? `shiftSignups` should be non-null.

2022-01-30 21:39 UTC, sherryhli commented on backend/graphql/index.ts
> +    isAuthorizedByRole(new Set(["VOLUNTEER"])) && isAuthorizedByUserId("userid")
I don't think `isAuthorizedByUserId` can be used as-is because it just checks the top-level argument with name `userId`, but in this case, we want a field called `userId` under an top-evel argument called `shifts` (which is an array). Would likely need a new middleware function to do this check.

@LenaNguyen Thoughts about making this a separate task as it was not included in the original ticket description?

2022-01-30 21:46 UTC, sherryhli commented on backend/graphql/index.ts
> +    isAuthorizedByRole(new Set(["VOLUNTEER"])) && isAuthorizedByUserId("userid")
We will likely need another ticket for sorting out access control anyways, we've been restricting nearly everything to admins only right now

2022-01-30 21:54 UTC, LenaNguyen commented on backend/graphql/index.ts
> +    isAuthorizedByRole(new Set(["VOLUNTEER"])) && isAuthorizedByUserId("userid")
yeah we can do it in a separate ticket

2022-01-30 22:13 UTC, sherryhli commented on backend/prisma/schema.prisma
>    user          User         @relation(fields: [userId], references: [id])
Another thought: we can just make the foreign key reference on the volunteers table rather than the base users table to enforce the "only volunteers can sign up" rule

2022-02-03 14:57 UTC, LenaNguyen commented on backend/prisma/schema.prisma
>    user          User         @relation(fields: [userId], references: [id])
That also works but I think our middleware for checking the role is good enough for now. We would still need to go through each shift to check that the volunteerID is the same as the volunteerID associated with the user in the token.

2022-02-03 14:58 UTC, LenaNguyen commented on backend/graphql/index.ts
> +    isAuthorizedByRole(new Set(["VOLUNTEER"])) && isAuthorizedByUserId("userid")
Made a ticket: #115

2022-02-03 22:58 UTC, hujoseph99 commented on backend/prisma/migrations/20220116032551_add_note_to_signup/migration.sql
> +/*
i believe that my latest update should already be greater than `20220128011600`

2022-02-03 23:00 UTC, hujoseph99 commented on backend/services/implementations/shiftSignupService.ts
> +        shiftSignups?.map((shiftSignup) =>
Hmmm, I don't think so. I just like adding it for safety

2022-02-05 03:46 UTC, LenaNguyen requested changes
just one small thing and then i'll approve :))

2022-02-05 03:46 UTC, LenaNguyen commented on backend/graphql/index.ts
> +    isAuthorizedByRole(new Set(["VOLUNTEER"])) && isAuthorizedByUserId("userid")
since the `isAuthorizedByUserId` doesn't work in this case, pls remove it

2022-02-05 04:35 UTC, sherryhli commented on backend/services/implementations/shiftSignupService.ts
> +        shiftSignups?.map((shiftSignup) =>
Hmm ok, not a big deal here but I'd rather avoid optional chaining when not necessary and have it fail in an obvious manner if an unexpected null value is passed

2022-02-05 04:53 UTC, hujoseph99 commented on backend/services/implementations/shiftSignupService.ts
> +        shiftSignups?.map((shiftSignup) =>
Hmm I see your point, I'll change it

2022-02-06 13:35 UTC, LenaNguyen approved these changes
Thanks for handling the changes!

2022-02-06 21:21 UTC, sherryhli approved these changes

2022-02-06 21:21 UTC, merged