Use scalar Date & DateTime instead of strings in handling Postings & Shifts
uwblueprint/sistering pull request #98
Opened 2022-01-21 02:59 UTC by lambo-liu

## Ticket link

Closes #91 

## Implementation description
* Added a `DateTime` GQL scalar type for handling dates in the format of "YYYY-MM-DD HH:mm"
* Updated existing Typescript variables to use the `Date` type instead of string
* Updated existing implementations of `Shift` and `Posting` services (and also removed string/date validations and conversions in these services). Updated instances of moment operations with built in JS
* Removed moment npm package as it is no longer needed.

## Steps to test
1. docker compose up
2. Verify that postings and shifts operations are working as expected

Example queries:
`mutation {
  createPosting(posting: {
    branchId: 4
    skills: [1]
    employees: [1]
    title: "test posting"
    type: INDIVIDUAL
    description: "test description"
    startDate: "2022-01-20"
    endDate: "2022-01-20"
    autoClosingDate: "2022-01-20"
    numVolunteers: 10
  }) {
    title
    type
    description
    startDate
    endDate
    autoClosingDate
    numVolunteers
  }
}`

`mutation {
  createShifts(shifts: {
    postingId: "1"
    times: [
      {
        startTime: "2021-01-01 03:00"
        endTime: "2021-01-01 04:30"
      },
      {
        startTime: "2021-01-04 13:15",
        endTime: "2021-01-04 15:30"
      },
      {
        startTime: "2021-01-07 07:30",
        endTime: "2021-01-07 15:45"
      }
    ],
    endDate: "2021-01-15",
    recurrenceInterval: WEEKLY
  }) {
    id
    postingId
    startTime
    endTime
  }
}`

## What should reviewers focus on?
* Correct use of Javascript date operations
* Did not modify result of any existing implementation

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2022-01-21 03:02 UTC, lambo-liu commented
My PR removes more lines than it adds 😔

2022-01-21 19:00 UTC, sherryhli requested changes
Looks great so far, thanks for doing some nice spring cleaning! 🧹✨ Just two action items:

1. Some modifications related to handling of timezones (see comments for more details)
2. @briantu recently made some changes to the return value of some posting service methods (e.g. [here](https://github.com/uwblueprint/sistering/blob/main/backend/services/implementations/postingService.ts#L232-L234)), could you rebase on `main` and remove the string conversions on dates?

2022-01-22 04:05 UTC, lambo-liu commented on backend/graphql/index.ts
> +  const regEx = /^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/; // YYYY-MM-DD HH:mm
Yeah for sure - I should have clarified this. I assumed we wanted the space instead of 'T', my bad 😅

2022-01-22 04:33 UTC, sherryhli reviewed
Thanks for addressing these so quickly, only a few minor things left!

2022-01-22 04:33 UTC, sherryhli commented on backend/graphql/index.ts
> +    new Date(dateTimeString).toISOString().slice(0, 16) === dateTimeString
Likewise here

```suggestion
    new Date(`${dateTimeString}:00`).toISOString().slice(0, 16) === dateTimeString
```

2022-01-22 04:33 UTC, sherryhli commented on backend/graphql/index.ts
> +    if (isValidDate(value)) return new Date(`${value}:00+00:00`); // value for server
I think we want this for the `DateTime` scalar below instead. This line and line 68 do not need to be changed

2022-01-22 04:33 UTC, sherryhli commented on backend/graphql/index.ts
> +    throw new Error(`${value} is not a valid date in format YYYY-MM-DD HH:mm`);
```suggestion
    throw new Error(`${value} is not a valid date in format YYYY-MM-DDTHH:mm`);
```

2022-01-22 04:33 UTC, sherryhli commented on backend/graphql/index.ts
> +        `${ast.value} was not a valid date in format YYYY-MM-DD HH:mm`,
```suggestion
        `${ast.value} was not a valid date in format YYYY-MM-DDTHH:mm`,
```

2022-01-22 04:33 UTC, sherryhli commented on backend/graphql/index.ts
> +    if (isValidDateTime(value)) return new Date(value); // value for server
Need the above changes here please 🙂

```ts
if (isValidDateTime(value)) return new Date(`${value}:00+00:00`);
```

2022-01-22 04:48 UTC, lambo-liu commented
> Thanks for addressing these so quickly, only a few minor things left!

OMG I'm so sorry I realized this right after I requested for your review - I should have ping'd you sorry for taking up your time 😢

2022-01-22 05:42 UTC, sherryhli requested changes

2022-01-22 05:42 UTC, sherryhli commented on backend/graphql/index.ts
> +    new Date(`${dateTimeString}:00`).toISOString().slice(0, 16) ===
I think we actually need to specify the timezone as UTC for this comparison to work, otherwise the ```new Date(`${dateTimeString}:00`)``` will be interpreted in the server's local time which may not match the original datetime string.

```suggestion
    new Date(`${dateTimeString}:00+00:00`).toISOString().slice(0, 16) ===
```

2022-01-22 05:42 UTC, sherryhli commented on backend/graphql/index.ts
> +    if (isValidDate(value)) return new Date(`${value}:00+00:00`); // value for server
```suggestion
    if (isValidDateTime(value)) return new Date(`${value}:00+00:00`); // value for server
```

2022-01-22 05:59 UTC, sherryhli approved these changes
🚢 🚢 🚢

2022-01-22 19:25 UTC, merged